### ISSUE TITLE
Invidious redirects to main page

### ISSUE THREAD

**Issue by oifj34f34f** [libredirect/browser_extension#1000]
Steps to reproduce the bug:

1. Install LibRedirect.
2. Set up a custom Invidious instance (e.g., https://yewtu.be).
3. Try to open https://www.youtube.com/watch?v=dQw4w9WgXcQ in the browser.
4. Instead of opening the video, it redirects to the home page.

This bug appeared in version 3.0.0 (everything worked in version 2.9.1 and below)

**Comment by ManeraKai** [comment]
Duplicate of https://github.com/libredirect/browser_extension/issues/996
