### ISSUE TITLE
Extra "/ " added to the end of domains leading to incorrect redirections

### ISSUE THREAD

**Issue by yazoink** [libredirect/browser_extension#1006]
Libredirect adds an extra forward slash at the end of my domains automatically which leads to pages being redirected to the home pages of the frontends instead of the specific URLs being redirected.

For example:
I will enter `https://inv.yazo.ink` to redirect to Invidious and Libredirect will automatically change it to `https://inv.yazo.ink/`. This leads to youtube links being redirected to `https://inv.yazo.ink/feed/popular` instead of `https://inv.yazo.ink/watch?v=etcetc`

**Comment by ManeraKai** [comment]
Isn't this a duplicate of https://github.com/libredirect/browser_extension/issues/996?

**Comment by yazoink** [comment]
What version was the fix committed to? I'm on 3.0.2

**Comment by ManeraKai** [comment]
Can you remove your custom instance and add it back?

**Comment by yazoink** [comment]
Works fine now!

**Comment by throwaway242685** [comment]
@ManeraKai

do you guys check the Codeberg repository? I made two issues there like a week ago.

**Comment by ManeraKai** [comment]
Yes we do.
