### ISSUE TITLE
How do I remove an instance that is redirecting

### ISSUE THREAD

**Issue by mastazi** [libredirect/browser_extension#1008]
a Redlib instance that no longer exists, is now redirecting to that website's homepage - rootdo.com

So I want to remove it, but I can't

1. the UI to select or deselect instances is no longer there
2. I cannot use "Remove + Switch Instance" because due to the redirection I am no longer on a Redlib url
3. since it's a redirection and not an error such as 404 or 503, the new dialog on error as per #936  is not triggered

**Comment by ManeraKai** [comment]
Then just remove it in the settings page.

**Comment by mastazi** [comment]
But as I explained in point 1 above, the settings page was no longer showing the list of instances - HOWEVER now the list is back so I'm closing this for now as I can no longer reproduce. I don't know why it was momentarily gone, I should have taken a screenshot. It was happening with all services, not just Reddit
