### ISSUE TITLE
Add Viewtube

### ISSUE THREAD

**Issue by davidcollini** [libredirect/browser_extension#115]
[Viewtube](https://github.com/ViewTube/viewtube-vue) is an alternative frontend for youtube with plans to implement basically all the features of invidious, cloudtube and Piped, so it's very feature-rich, the only problem is that the project is slow, but multiple commits are made basically everyday, so I don't think that speed will be much of an issue for long

**Comment by IronMaltese** [comment]
@mauriceoegerli @cyacedev here's a ping to the developers to make sure they're aware of this implementation

**Comment by Kotuklion** [comment]
It's worth mentioning that viewtube doesn't proxy all requests yet, video playback is still being accessed from google servers (at least i think so after looking into the network logs)
![image](https://user-images.githubusercontent.com/36082262/160009338-ceaa3705-48a6-492b-baea-a2c1b634e4e5.png)

**Comment by ManeraKai** [comment]
Are there any instances?

**Comment by IronMaltese** [comment]
Viewtube.io

**Comment by ManeraKai** [comment]
no I mean other instances?

**Comment by IronMaltese** [comment]
I'm pretty sure there's at least two more public ones, but I can't find them right now

**Comment by ManeraKai** [comment]
Won't add it as it doesn't have an instances list.

**Comment by sereksim** [comment]
> Won't add it as it doesn't have an instances list.

They added an instances list at https://viewtube.wiki/about/instances
Is that sufficient or does it have to be in json?

**Comment by ManeraKai** [comment]
>  Is that sufficient or does it have to be in json?

I can see it as a Markdown file here: https://github.com/ViewTube/wiki/blob/main/content/1.about/1.instances.md

**Comment by ManeraKai** [comment]
None of the instances are working though?

**Comment by darlopvil** [comment]
viewtube.io is working smoothly atm
vt.ra-phi.ch behaves oddly though....
and dev.viewtube.io redirects to the main instance...

You need at least a full list of working instances?

**Comment by ManeraKai** [comment]
One is enough for now.
