### ISSUE TITLE
Add support for ImGinn, an Instagram frontend

### ISSUE THREAD

**Issue by quarkl8** [libredirect/browser_extension#446]
[https://imginn.com](https://imginn.com)
(I found a few other services with the same name, but this website has been around the longest so I assume it's the original)

So far I've been using ImgInn by The URL exactly follows Instagram's pattern, unlike Bibliogram which adds a /u when dealing with profiles. I don't want to have to keep deleting the /u though.

**Comment by EsmailELBoBDev2** [comment]
is it open source?

**Comment by ManeraKai** [comment]
This is a screenshot from Hygna:
![image](https://user-images.githubusercontent.com/40805353/190724788-9bc0c685-6b4e-4eb5-9e57-293c439f123e.png)
I think it explains itself why we won't add it. It's not a "privacy" frontend.

**Comment by mamamia5x** [comment]
Woah, what even is Hygna? I tried looking it up and I can't find anything about it. Is this a paid service or is it free online? This looks great for some projects I'm working on.

**Comment by EdwardLangdon** [comment]
You can see it in the first comment itself. It's a Free Instagram Public Archiver.
