### ISSUE TITLE
Feature: export/import settings to/from sync storage

### ISSUE THREAD

**Issue by mpeter50** [libredirect/browser_extension#576]
Initially I wanted to suggest a feature to allow syncing settings through the sync mechanism of Firefox, but I've seen in other issues that you had that earlier, and it didnt work flawlessly.

However, I think it could still be doable without much hassle.
On the "General" settings page you already have options to export and import the settings through the file system. Do you think it would be possible to have an option that uses the [sync storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) instead of files as the export/import target?
uBlock Origin [does something similar](https://github.com/gorhill/uBlock/wiki/Cloud-storage) too: it does not actively work from the sync storage, it only uses that to share the configuration between devices of the user, which can be manually applied.

Of course, it is ok to not try to "merge" the already existing state in sync storage with the current one.
On the contrary: it may be a good idea to reset the sync storage before every export, so the that the stored state never gets mixed with an old state that was exported earlier.

Making this possible would help those who use Firefox on multiple devices (excluding phones), as keeping the settings in sync would be much easier, even if still not fully automatic, as now the user would not need to use some other means of transferring the configuration files to the other devices.

**Comment by ManeraKai** [comment]
This may happen and may not, but not a priority rn.

**Comment by ManeraKai** [comment]
So you mean copy them as a backup to sync, then have an option of importing like "import from sync" instead of "import from file".

**Comment by mpeter50** [comment]
Yes, basically
