### ISSUE TITLE
"Embed Frontend" feature for youtube

### ISSUE THREAD

**Issue by Sentenza-Git** [libredirect/browser_extension#624]
Since version 2.5.0 it is no longer possible to activate the FreeTube redirection and at the same time the invadious redirection with the option "Embed Frontend".

![ 6-02-2023_22-51-41](https://user-images.githubusercontent.com/124632589/217096189-f588055c-2861-409a-a2e4-609ffcc64ff4.png)

OS: Linux Mint 20.3
Firefox 109.0.1
FreeTube 0.18.0
libredirect 2.5.x

**Comment by ManeraKai** [comment]
Will be closed in favor of [Frontends Manager](https://github.com/libredirect/frontends_manager), having an app as a replacement for a website is not a good idea, iframes will be one of the problems that will pop up. Frontends Manager will solve this hopefully.

**Comment by XxTriviumxX** [comment]
> Will be closed in favor of [Frontends Manager](https://github.com/libredirect/frontends_manager), having an app as a replacement for a website is not a good idea, iframes will be one of the problems that will pop up. Frontends Manager will solve this hopefully.

Youtube redirect is not available on Frontend Manager. Why would you want to close this issue?

> having an app as a replacement for a website is not a good idea

Why are you promoting the Frontend Manager app? It's an app.

I am most likely completely off with my reply to be honest.  I'm just comfused.

**Comment by ManeraKai** [comment]
> Youtube redirect is not available on Frontend Manager. Why would you want to close this feature request?

I'm working on adding Invidious and Piped to it.

**Comment by XxTriviumxX** [comment]
Will you consider adding the feature to the libredirect extension too?  

As for the [Frontends Manager](https://github.com/libredirect/frontends_manager) App it is only available on debian based OS. Can you push an AUR for the Arch linux users?  Or at least flatpak?

I have to use  RSS feeds to get notified for new versions for the appimage ... and the appimage requires me to install docker too, which i don't really want in my system.. but i guess i can install it for this tool.

**Comment by ManeraKai** [comment]
> Will you consider adding the feature to the libredirect extension too?

Which feature?

> As for the [Frontends Manager](https://github.com/libredirect/frontends_manager) App it is only available on debian based OS. Can you push an AUR for the Arch linux users? Or at least a flatpak?

Flatpak will be supported in future once I figure that out.

> edit: that app doesnt work. libreddit is not redirected.

Go to setting s in the extension and change "Indtance" to "localhost"

**Comment by XxTriviumxX** [comment]
Im talking about the feature like in the picture above. You removed the feature of putting freetube frontend and invidious enbed frontend. Is there any hope you can put it back on with the extension?

**Comment by XxTriviumxX** [comment]
works great! But, please keep working on the browser extension...

I have a question though..  how do you keep those frontends up to date? Do they get updated at the same time the app itself gets updated?

**Comment by ManeraKai** [comment]
> works great! But, please keep working on the browser extension... its awesome!

bruh ofc I will be working on the extension xD. The app is just for hosting the frontends not for redirecting.

> I have a question though.. how do you keep those local frontends up to date? Do they get updated at the same time the app itself gets updated?

Well I'm still working on this thing, but it's completely separated from the AppImage, they get downloaded from here: https://github.com/libredirect/frontends_binaries

> edit: The appimage made me download "caddy" too. How does it keep it updated?

Caddy is like Nginx, a server manager. It allows me to have "libreddit.localhost:8080" "rimgo.localhost:8080" urls on the same port.

**Comment by XxTriviumxX** [comment]
> bruh ofc I will be working on the extension xD.

That's great!!  i thought  you were dumping this feature request and put it in the app and the app only because you said:

> Will be closed in favor of [Frontends Manager](https://github.com/libredirect/frontends_manager)

Another thing, the appimage downloaded caddy... where is caddy and how do i get rid of it?  By simply deleting the appimage?

**Comment by ManeraKai** [comment]
> That's great!! i thought you were dumping this feature request and put it in the app and the app only because 2 weeks ago you commented

I really want to but your making me feel guilty.

**Comment by Victor239** [comment]
I agree with the OP here - I really enjoy FreeTube as it let's me locally subscribe to channels, create categories and star favourites. It's a superior alternative to the web-based frontends with many features, so I want to opportunistically use it whenever possible.

The UI for LibRedirect's YouTube settings trying to simultaneously use FreeTube but also redirecting embeds to another frontend has been weird for a while, but I thought it was instead going to be resolved like this:

- New dropdown setting called `Desktop App` with the choices of "Disabled" (default), "FreeTube", and potentially other desktop apps like KDE's [PlasmaTube](https://flathub.org/apps/org.kde.plasmatube) and [Tubefeeder](https://flathub.org/apps/de.schmidhuberj.tubefeeder).
- If the setting is changed from "Disabled", then `Redirect Type` setting is forced to "Only Embedded", and uses whatever is set in the `Frontend` setting.

Would love to see a similar approach for all frontends eventually - it doesn't seem too difficult to allow users to use desktop apps whenever possible, and it reduces the burden on community servers.

**Comment by XxTriviumxX** [comment]
> I really want to but your making me feel guilty xD

But it was a super cool feature!!!!  LOL Jokes aside... Why did it get removed? Was it problematic?

> Another thing, the appimage downloaded caddy... where is the downloaded caddy and how do i get rid of it? By simply deleting the appimage?
> 
> edit: arch linux pc.

plocate was buggy yesterday. It got fixed this morning with its last patch.

I found caddy there:

```
$ locate caddy
/home/user/.config/caddy
/home/user/.config/caddy/autosave.json
/home/user/.local/share/org.libredirect.frontends-manager/caddy
/home/user/.local/share/org.libredirect.frontends-manager/caddy/caddy_linux_amd64
```

In order to remove caddy, do i simply remove those dirs and files?

**Comment by ManeraKai** [comment]
@XxTriviumxX It's just here `~/.local/share/org.libredirect.frontends-manager/caddy/caddy_linux_amd64`

**Comment by ManeraKai** [comment]
@Victor239 The thing is Desktop Apps are meant to be used without the browser, but we're doing the opposite.
The thing that I really wanna see is FreeTube opened in a browser tab. It's already built using Electron so this should be possible, and it will be a lot better to use imo (bc of embeds and all the other things a browser has). In other words I want to encourage using frontends that are "headless but run in the browser rather than in a separate window".

**Comment by Victor239** [comment]
> The thing is Desktop Apps are meant to be used without the browser, but we're doing the opposite.

I use FreeTube without an open browser daily (saves memory and less distractions), but when I do come across a video in my browser I'm also able to easily view it in my FreeTube, where I can save it and it's added to my local history. It's seamless integration, and best of both worlds.

Web-based frontends on the other hand require an open browser if you use Firefox like I do (as it has poor PWA support).

> The thing that I really wanna see is FreeTube opened in a browser tab. It's already built using Electron so this should be possible, and it will be a lot better to use imo (bc of embeds and all the other things a browser has).

Some frontends are limited by Web APIs however, which makes desktop apps more suitable in some cases. For example there's the [FreeTube Cordova](https://github.com/MarmadileManteater/FreeTubeCordova) fork, which turns it into a web app and then an Android app. It isn't able to use the [Local API](https://docs.freetubeapp.io/usage/local-api/) for streaming from YouTube, and instead has to rely on the Invidious API to stream from an instance. 

If that can be resolved however I do agree it'd be interesting to see FreeTube in a browser, it'd be a better frontend than Invidious. But I can still imagine several limitations, like it not being able to opened directly from my desktop and instead requiring the Frontend Manager to be initialised first. 

> In other words I want to encourage using frontends that are "headless but run in the browser rather than in a separate window".

I understand wanting to primarily support web-based frontends, but this would also mean cutting off useful desktop frontends from being used until work is done to rearchitect them to also work as web apps and then the limitations that come with it.

In the meanwhile I want to use all the features of FreeTube, and not settle for Invidious. I want to use LBRY, not Odysee. I want to use Giara, not Teddit. 

Sometimes I even get a bunch of links to YouTube music videos and wish I could have them open in my YouTube -> MP3 downloader desktop app. 

I hope you'll consider allowing users to still use a desktop app if they wish.

**Comment by XxTriviumxX** [comment]
> to encourage using frontends that are "headless but run in the browser rather than in a separate window".

The option for a desktop app is not a huge deal to make and maintain. The real thing to encourage here is online privacy.

**Comment by XxTriviumxX** [comment]
can't wait to use the feature and ditch the privacy redirect extension. Thank you for reconsidering the feature.

**Comment by ManeraKai** [comment]
@Victor239 Your points are really valid, but just one question about the implementation, have you used LibRedirect prior to [2.3.4](https://github.com/libredirect/browser_extension/issues/624#issue-1573349801). Isn't the having an "Embed frontend" selection a better UI design?

**Comment by Victor239** [comment]
Could you post a screenshot of it what that was like? In it's previous version I remember that if you select "FreeTube" as the frontend then you weren't able to specify which other frontend would handle the embeds, which is why I suggested the alternative UI options above.

**Comment by XxTriviumxX** [comment]
> Could you post a screenshot of it what that was like?

![154353435-7f454c98-d74e-4726-b9e5-7e92aee0a05a](https://github.com/libredirect/browser_extension/assets/118479520/1fc829b2-467f-4e65-bac8-a53a2e9cbd23)

**Comment by ManeraKai** [comment]
The last design v2.3.4: https://github.com/libredirect/browser_extension/issues/624#issue-1573349801

**Comment by Victor239** [comment]
Ah I see, yeah that UI looks fine actually. I must be just remembering an even older version.

**Comment by ManeraKai** [comment]
Alright, I just hope nothing will break bc I changed so many sensitive things. Will need some testing before release:
![screenshot](https://github.com/libredirect/browser_extension/assets/40805353/d7d13a24-69b2-45f8-bcd7-e81b35ceb283)

**Comment by XxTriviumxX** [comment]
> I changed so many sensitive things

i didn't know it was THAT complicated.. but thanks a bunch! I will contribute if i ever find bugs.

**Comment by ManeraKai** [comment]
@XxTriviumxX See our [matrix](https://matrix.to/#/#libredirect:matrix.org) room for v2.7.0:
![image](https://github.com/libredirect/browser_extension/assets/40805353/627863ee-78ed-49ac-9138-b5d336a6918e)

**Comment by pm4rcin** [comment]
@ManeraKai regarding embedded frontend what about adding option to use any frontend (invidious/piped)? Since it's embed I don't think many people care which frontend it actually is since they just want to have the video loaded.

**Comment by XxTriviumxX** [comment]
>  I don't think many people care which frontend it actually is since they just want to have the video loaded.

it matters.  people should have the power to choose between invidious and piped.. as a matter of fact, invidious has been broken for days now.  piped is the only viable workaround

**Comment by pm4rcin** [comment]
> > I don't think many people care which frontend it actually is since they just want to have the video loaded.
> 
> it matters. people should have the power to choose between at least invidious and piped.. as a matter of fact, invidious has been broken for days now. piped is the only viable workaround

I don't mean removing but adding 3rd choice as another option. ;)

Regarding Invidious being broken I don't know what you're talking about. I've tried random instance just now and it works. Maybe your instance is broken?

**Comment by ManeraKai** [comment]
> I don't mean removing but adding 3rd choice as another option. ;)

No this will over complicate things and won't scale well. I need to know what frontend the user is using to determine the correct function to execute for converting the url.

**Comment by XxTriviumxX** [comment]
they mostly use invidious and piped for enbedded.

**Comment by XxTriviumxX** [comment]
So, is this button coming back soon?
![246873104-1fc829b2-467f-4e65-bac8-a53a2e9cbd23](https://github.com/libredirect/browser_extension/assets/118479520/a5b45358-a650-4124-88d1-4d89545888e9)

**Comment by ManeraKai** [comment]
It is already there, you just need to choose `both` in the `Redirect Type`

**Comment by XxTriviumxX** [comment]
https://github.com/libredirect/browser_extension/issues/624#issuecomment-1597882298

you're the source of the left screenshot. i thought you were working on that :(

**Comment by ManeraKai** [comment]
![image](https://github.com/libredirect/browser_extension/assets/40805353/6ec3e1b2-11aa-4880-a147-3ad566c2498b)

**Comment by XxTriviumxX** [comment]
here. i used "both".

still nothing...



![both](https://github.com/libredirect/browser_extension/assets/118479520/d43e3743-d353-4db4-9d62-9d01290466e1)

**Comment by XxTriviumxX** [comment]
i only have front end..

not frontend AND embed options

**Comment by ManeraKai** [comment]
bc you are using Piped, oh I see now. The feature is only for Freetube bc it doesn't support embeds.

**Comment by XxTriviumxX** [comment]
no... look closer. i only have ONE "frontend"  drop down menu .. .you have TWO!! both FRONTEND and EMBEDDED drop down menus.

you never implemented the change for the users. ONLY YOU have that function and no one else.

here's with invidious:



![both invidious](https://github.com/libredirect/browser_extension/assets/118479520/e708845d-a0f2-4560-ba04-7ecf05f65dba)

**Comment by XxTriviumxX** [comment]
nevermind.   i used piped.. because i had to use another extension to handle freetube. my bad
