### ISSUE TITLE
Site suggestion: down detectors like downforeveryoneorjustme.com

### ISSUE THREAD

**Issue by cubical8569** [libredirect/browser_extension#658]
There is at least one open-source down detector site: isitup.org. Many people don't know about it and still use downforeveryoneorjustme.com and alike.

It would be cool if down detectors were added in the extension. Thank you for the project.

**Comment by ManeraKai** [comment]
[libre](https://librespeed.org/) too

**Comment by ManeraKai** [comment]
Gave it a second, or a 10th thought, I don't think I'll add it's very different from librespeed's case.
