### ISSUE TITLE
How to use the "Paste Text" functionality ?

### ISSUE THREAD

**Issue by m040601** [libredirect/browser_extension#671]
This has been asked before here, https://github.com/libredirect/libredirect/issues/629

But it was closed. I apologize, but I dont understand it still.

Someone said there,

> Press on the Frontend text to know more about PrivateBin

This does not work on my install. Clicking on "Frontend" does nothing.

This "Paste Text" and the "Send Files" functionality **needs to be better explained in the README**. They are "obvious" to the developers of Libredirect. But **they are not "obvious" for new users**. They are a little bit different than the other "classical" redirect functionalities.

I confess, being a long time user and fan of Libredirect I still have the same question as the original poster. I know what "PrivateBin" and I know there are instances running it in different domains. And those instances are listed in my Libreredirect.

I just  cant understand how to "use it" with Libredirect.

What does it "redirect" from ?
How do I use it when I have copied something to my clipboard and want to paste it ?

Also, why is it that when I paste this  to the address bar, nothing happens,

```
http://paste.libredirect.invalid/
```

I was expecting to be redirected to one of those instances.

And yes I have all these "enabled" boxes checked on my configuration.

But if I open this url,

`http://send.libredirect.invalid/`

or this

`http://search.libredirect.invalid/`

It does work as I expected. And I can use it as a search engine in Tridactyl or other Firefox add-ons. Really great functionality. 

This ".libredirect.invalid" "domain" is a very clever trick. Its different "http://XYZ.libredirect.invalid/" "urls" should be mentioned in the README. It took me a while to notice them in the address bar and understand the "mechanics" of it.

**Comment by ManeraKai** [comment]
Pressing on Frontend should be working but bc of a bug it's not.

**Comment by ManeraKai** [comment]
> This ".libredirect.invalid" "domain" is a very clever trick. Its different "http://xyz.libredirect.invalid/" "urls" should be mentioned in the README. It took me a while to notice them in the address bar and understand the "mechanics" of it.

Makes sense.
