### ISSUE TITLE
BetterChatGPT

### ISSUE THREAD

**Issue by IntinteDAO** [libredirect/browser_extension#673]
I don't know if this counts as an alternative. BetterChatGPT looks like an alternative interface to ChatGPT. So it is possible to create a more anonymous ChatGPT, although it requires our (possibly the site creator's?) API key.

https://github.com/ztjhz/BetterChatGPT

Demo instance: https://bettergpt.chat/

**Comment by toyboatcash** [comment]
https://freechatgpt.chat/ seem to also work.

**Comment by ManeraKai** [comment]
So?
