### ISSUE TITLE
[Feature Request] Configuration option to open redirect tabs in the background

### ISSUE THREAD

**Issue by jve-engineering** [libredirect/browser_extension#675]
Can you please add an option to control the behavior of how the new tab opens on a redirect action?
The current implementation always opens the new tab at the very end of the list and changes the focus directly to the new tab.
This interrupts the reading flow, e.g. if in a longer article links to background material are embedded, which one would like to read only afterwards.

It would be good if there was a way to set the behavior as the Firefox browser itself [offers it](http://kb.mozillazine.org/About:config_entries):
`browser.tabs.loadInBackground`
`browser.tabs.insertRelatedAfterCurrent`

At least the first point "load in background" should be technically possible, e.g. the "[Web Archives](https://github.com/dessant/web-archives)" addon has such an [option](https://github.com/dessant/web-archives#screenshots).

**Comment by ManeraKai** [comment]
Are you talking about those?
![Screenshot_20230516_084847](https://github.com/libredirect/browser_extension/assets/40805353/a5a9e58a-3f4a-4acb-a520-9b31dcb4ffb8)

**Comment by jve-engineering** [comment]
Hello @ManeraKai  and thank you for your feedback. Yes, I usually use the entry in the Context Menu to open such links. I'm not sure if it makes sense for consistency reasons to make e.g. the `active` parameter configurable for all `browser.tabs.create()` calls, so that all new tabs behave identically.

**Comment by ManeraKai** [comment]
I think I'll make it simply as another menu option bc it's a confusing setting.
