### ISSUE TITLE
[Feature request] Add POST option for the search engine.

### ISSUE THREAD

**Issue by amogusussy** [libredirect/browser_extension#677]
Please add an option to use POST requests instead of GET for the search engine.

**Comment by ManeraKai** [comment]
Do you want this request bc:
1. You really need to have long search keywords that requires POST?
2. You have some instances that have their default setting as POST?

**Comment by amogusussy** [comment]
I want it because POST is more private.
If you open your history and look at requests for search engines that use GET, you can see whatever search terms are used, whereas with POST, nothing, aside from the base URL (e.g. `https://searx.work/search`) is shown.

**Comment by ManeraKai** [comment]
I don't think it's possible, I read the [webRequest BlockingResponse](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/BlockingResponse) API but there's nothing about it. I also tried installing [startpage extension](https://addons.mozilla.org/en-US/firefox/addon/startpage-private-search/) bc they have POST as an option, but it doesn't work when you type in the address bar.
