### ISSUE TITLE
Not Duplicate: Non-removable Context Menu Entry on Links

### ISSUE THREAD

**Issue by emrakyz** [libredirect/browser_extension#679]
I can't even remove this entry through userChrome.css

Inspector shows this ID: **7esoorv3_alefvanoon_anonaddy_me-menuitem-0**

But that ID can't be added into userChrome.css file. I can for example remove the entry for uBlock Origin with its ID: **#ublockU_raymondhill_net_uBlock0-blockElement**

![image](https://user-images.githubusercontent.com/89175311/232332384-4c86a649-46be-4aa2-9197-2fd64bb69356.png)

**Comment by ManeraKai** [comment]
Try this: 7esoorv3@alefvanoon.anonaddy.me

**Comment by emrakyz** [comment]
@ManeraKai 

Hi! Thanks for help.

I have added this with no success:
#7esoorv3@alefvanoon.anonaddy.me {
    display: none !important
}

I have also tried 7esoorv3@alefvanoon.anonaddy.me-0 and 7esoorv3@alefvanoon.anonaddy.me0

It doesn't get the syntax highlighting, probably because it doesn't start with a letter but a number. This can be seen in the attached image:

![image](https://user-images.githubusercontent.com/89175311/232339784-8131ba11-2e01-4283-9bcb-93b2aceff463.png)

**Comment by IDUnavailable** [comment]
@emrakyz the partially-cursive fixed-width font is freakin me out but I do agree with this request. I'm really only using libredirect to automatically redirect a couple of sites like Twitter and don't want anything related to the extension in my context menus.

**Comment by emrakyz** [comment]
@IDUnavailable 
> @emrakyz the partially-cursive fixed-width font is freakin me out

Haha :) It's "Operator Mono". It's actually a paid programming font but you can find it everywhere I guess.
Being partially cursive, it can offer extra distinction for some cases. Normally, only italics have cursive features. Interestingly userchrome.css has a lot of them :)
