### ISSUE TITLE
Update wants permission to read bookmarks

### ISSUE THREAD

**Issue by foerster-rwth** [libredirect/browser_extension#685]
I wonder for how many more days I will have to decline -- every single day -- the installation of the update before there is a way to opt out of that permission. I remember reading a conversation somewhere with one of the authors of libredirect where he suggested the introduction of such an opt-out.

Is there any news on this?

**Comment by ManeraKai** [comment]
Browser Extensions aren't like android apps where you can ask for a specific permission. You either accept all permissions, or decline the "version update" altogether and keep on using the old version.

**Comment by acidghost** [comment]
Wow, this was a terrible reply, @ManeraKai. This was just after a 3 seconds Web search: https://support.mozilla.org/en-US/kb/manage-optional-permissions-extensions.

Are you planning to implement opt-in permissions for the bookmarks feature or not?

**Comment by ManeraKai** [comment]
oh one second that's really nice, and found [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) too. ok I'll re-open the issue. Thanks you so much really.

**Comment by ManeraKai** [comment]
I will also do this for contextMenus: https://github.com/libredirect/browser_extension/issues/679

**Comment by ManeraKai** [comment]
Fixed here: https://github.com/libredirect/browser_extension/issues/688
