### ISSUE TITLE
Add all instances button

### ISSUE THREAD

**Issue by theamazing0** [libredirect/browser_extension#686]
Feature request - add a button to add all the instances from the clearnet instance list to favorites and another button to clear the favorites list.

**Comment by ManeraKai** [comment]
This will be closed in favor of [LibRedirect Frontends Manager](https://github.com/libredirect/frontends_manager).

**Comment by acidghost** [comment]
How are the two things related?

OP is asking for a button to automatically select all 3rd party instances.
You are suggesting a tool to spawn and manage local instances.

**Comment by ManeraKai** [comment]
@acidghost Yes bc:
- Automatically redirect offline instances
- Unify settings across all instances
- Ping instances
- Update the instances list
- Add all instances button
- Trusting unknown instances
- What first instance should a newbie user start with?

All those problems are bc of relying on unknown 3rd part instances. So I'm trying to fix all this by creating a trust-less model (hosting them yourself easily).

**Comment by theamazing0** [comment]
I think @ManeraKai has a valid point in the problems that come with it, but a seperate "libredirect profile generator" that checks instance speed and if its online or something of the sort would be useful for people who don't want to use the frontend manager or don't use a specific frontend often.

**Comment by ManeraKai** [comment]
The frontend manager is a lightweight software and it's 5MB in size. Then for the web server ([Caddy](https://caddyserver.com/)) it downloads it and it's about 30MB. Then if you just use a single frontend ex LibReddit, you just download that frontend binary NOTHING ELSE. So it's a pretty light weight and as much de bloated as it can be.

We actually had a "profile generator" and an upgradable instances list and even a button where it had a threshold for disabling or enabling instances, but it just created complex code and bugs and all the problems I mentioned above.

Imo for future, if peo
