### ISSUE TITLE
Extension stops working after deleting folder

### ISSUE THREAD

**Issue by maxchristman** [libredirect/browser_extension#687]
I tried installing Libredirect to the Brave browser on macOS. I following the given instructions:

1. Download the latest zip file [libredirect-2.5.4.zip](https://github.com/libredirect/libredirect/releases/download/v2.5.4/libredirect-2.5.4.zip)
2. Unzip it with `Auto detect subfolder`
3. Go to Extension Manager, and enable developer mode
4. Click Load unpacked. Select and open libredirect-2.5.4/src/

There's no `Auto detect subfolder` option on macOS, but I don't think this matters. 

Once I delete the folder that I extracted, the extension stops working. Is there any way to have the extension stored with the browser itself? It's not optimal to keep a folder lying around in my Downloads just to use an extension.

**Comment by ManeraKai** [comment]
The macOS is a hack you can say for making the browser allow you to install an unknown unsigned extension. It's like you're installing it in debug mode.
More info: https://github.com/libredirect/browser_extension/issues/597

**Comment by ManeraKai** [comment]
If you figured out a way of installing it (as a .crx), then plz open an issue for it. We already figured it out for Windows and Linux.

I'm closing this issue.
