### ISSUE TITLE
Support for Kiwix Offline browsing

### ISSUE THREAD

**Issue by TheWanderer1983** [libredirect/browser_extension#690]
How about support for offline versions of repositories also?

For example if a frontend is down or you would just rather browse completely local. You can load up a ZIM repo and browse. It has support for many websites. Here is the library https://library.kiwix.org/?lang=eng

and here is the browser extension as well as web app.
https://www.kiwix.org/en/downloads/browser-extensions/

**Comment by ManeraKai** [comment]
Which frontend do you wanna browse using Kiwix? The frontends we're redirecting from are for social media sites that are constantly updating, they are not wiki's.

**Comment by andradadad** [comment]
If you download the .zim of wikipedia/wikitionary, they're a good way to escape browsing their servers at all.

**Comment by ManeraKai** [comment]
ok I understand that, but how do you want it for a frontend? Which frontend you want exactly? and which content you wanna save offline exactly?

**Comment by TheWanderer1983** [comment]
https://library.kiwix.org/?lang=eng 
It's a frontend viewer with the online library. Another one Installable Progressive Web App (PWA)
https://pwa.kiwix.org/ i

**Comment by ManeraKai** [comment]
> For example if a frontend is down or you would just rather browse completely local

This is simply impossible, you can only browse the things you downloaded through the kiwi library you mentioned. You can't browse Invidious or Piped if your internet went off, if you wanna do so, then you should download the whole YouTube database to a zim file.

Like Kiwix is a great project, but it's not a "frontend", it's something completely different.

I'm closing the issue.

**Comment by TheWanderer1983** [comment]
Correct you can't browse if your internet is down. I guess the issue here is a was a wording issue. Take this example, Wikipedia. Lets say Wikiless was down. Libredirect could than offer to download an offline version (ZIM) from kiwix library for viewing. Or you could provide the option to download an offline version instead of using a front-end like wikiless for people who don't want to interact with the servers at all.

**Comment by ManeraKai** [comment]
> Correct you can't browse if your internet is down. I guess the issue here was a wording issue. Take this example, Wikipedia. Lets say Wikiless was down. Libredirect could then offer to download an offline version (ZIM) from kiwix library for viewing. Or you could provide the option to download or preference an offline version instead of using a front-end like wikiless for people who don't want to interact with the servers at all.

Still out of the scope of LibRedirect.
