### ISSUE TITLE
Add vixip

### ISSUE THREAD

**Issue by TechnicalSuwako** [libredirect/browser_extension#693]
Privacy UI for Pixiv
https://pixiv.owacon.moe
https://gitler.moe/suwako/vixip

**Comment by ManeraKai** [comment]
At least a checkbox for NSFW content in a settings page like LibReddit that is disabled by default in the code:
![image](https://github.com/libredirect/browser_extension/assets/40805353/539fefea-02db-4a6c-9c3c-fc417a1e5471)
Don't wanna risk all the other frontends.

**Comment by ManeraKai** [comment]
Re-open the issue if there's any updates. I'm closing it for now.

**Comment by TechnicalSuwako** [comment]
その場合、検閲のないフォークを作っておきました。
https://gitler.moe/suwako/libreredirect

**Comment by NoPlagiarism** [comment]
> その場合、検閲のないフォークを作っておきました。 https://gitler.moe/suwako/libreredirect

It's not censorship... It's just SFW.
