### ISSUE TITLE
Removal of the SearX instances from searx.space

### ISSUE THREAD

**Issue by unixfox** [libredirect/browser_extension#700]
Please see: https://github.com/searxng/searx-instances/discussions/336

Summary: The support for SearX instances will be removed from searx.space on the 1st September 2023.

**Comment by ManeraKai** [comment]
So for SearX this? https://github.com/searx/searx-instances/blob/master/searxinstances/instances.yml
And for SearXNG, it will be the same old link: https://searx.space/data/instances.json

**Comment by unixfox** [comment]
Correct
