### ISSUE TITLE
Opening a link with Firefox closed doesn't redirect

### ISSUE THREAD

**Issue by Insprill** [libredirect/browser_extension#701]
If Firefox is closed and a link is opened, Libredirect does not redirect the link.

To reproduce the issue, enable redirection for a site like YouTube, close Firefox, and try opening a YouTube link from another application or the command line. Firefox will open to the original YouTube site instead of the redirected site. However, the link will be properly redirected if the site is opened again while Firefox is already open.

(Tested with Firefox Developer Edition 114.0b2)

**Comment by ManeraKai** [comment]
Yes I remember this issue, it's a really old issue and I unfortunately couldn't find a fix for it. LibRedirect can't see that first url at all. This problem is on the Firefox side (not exposing the first launch url to extensions).
