### ISSUE TITLE
Skip offline instances

### ISSUE THREAD

**Issue by nobie137** [libredirect/browser_extension#702]
Redirect to another instance if it's down automatically.

**Comment by JDJoe** [comment]
The percentage of off line instances has got to the point where this extension has become a serious PITA to use.

**Comment by ManeraKai** [comment]
Well that's why I'm creating [LibRedirect Frontends Manager](https://github.com/libredirect/frontends_manager)

**Comment by ManeraKai** [comment]
I'm gonna close this issue in favor of [LibRedirect Frontends Manager](https://github.com/libredirect/frontends_manager), a stable version will be released soon hopefully, for now you can download the [beta version](https://github.com/libredirect/frontends_manager/releases/tag/v0.0.7)

**Comment by mu22le** [comment]
I'm not too happy about this decision, the place where I need libredirect
the most is my phone's, and  it's not like I can realistically host these
front-ends on it.

Il Dom 14 Mag 2023, 13:15 ManeraKai ***@***.***> ha scritto:

**Comment by ManeraKai** [comment]
@mu22le LibRedirect isn't officially supported for mobile browsers.
Try the other solutions available if this was a deal breaker: [Privacy Redirect for Apple](https://apps.apple.com/us/app/privacy-redirect/id1578144015?platform=iphone), [UntrackMe](https://f-droid.org/packages/app.fedilab.nitterizeme/)

**Comment by mu22le** [comment]
It's too bad, because I routinely use it on my android, and it works very well (when the instances I use do not die). Neither untrackme nor privacy redirect would do the same job.

**Comment by Clozent** [comment]
Why is this closed? Hosting your own front-ends isn't a replacement for public instances, even if it becomes a non-hassle.
Here are a few reasons I thought of:

1. What if, for whatever reason, I don't want to use my computer's resources to host a front-end instance?
2. What if I don't want my IP address exposed to the services I'm accessing (the ones these front-ends are made for!)?

I don't want to land on an unusable instance half the time, and for the solution to be "Oh, just host it yourself". Is checking for an error message really that difficult?
