### ISSUE TITLE
bug: YouTube unsupported path redirects to random instance

### ISSUE THREAD

**Issue by SethFalco** [libredirect/browser_extension#703]
### Steps to Reproduce

Settings for YouTube redirects:

| | |
|---|---|
| Enable | true |
| Show in popup | true |
| Frontend | Invidious |
| Redirect Type | Only Not Embedded |
| Unsupported paths handling | bypass |
| Favorite instances | https://yewtu.be |

1. Visit 
https://www.youtube.com/redirect?event=channel_banner&redir_token=QUFFLUhqa1dRRXhHT2lYRWQta2w3YWZwSExLYVduZFZld3xBQ3Jtc0tuaDROUlNtZFhiU0xGM19GMmFMQXZFWGlKTktWTlViSW1sWjVrci1QZ3F1VXV0RUxTZ3J2aFk1TEJreENsXzgtMXEwQUtzSVNzR3FTempabVZvVFpITnNWWk5CX0RIR19Rbjhscnp6c1hYMXNoQzhfQQ&q=https%3A%2F%2Ffractaldreamers.bandcamp.com%2F

### Actual Behavior

Takes me to a random instance's popular page. (Ignores my settings!)

The only instance I have configured is yewtu.be, yet clicking this will take me to pages like:
* https://invidious.slipfox.xyz/feed/popular
* https://iv.ggtyler.dev/feed/popular
* https://invidious.sethforprivacy.com/feed/popular
* https://y.com.sb/feed/popular

### Expected Behavior

It should follow the intended redirect path. The `q` query parameters in the URL.

In this case, it's: https://fractaldreamers.bandcamp.com/

### Context

Sometimes, for whatever reason, I need to be on youtube.com using the respective button available from Invidious.

For example, using the **View channel on YouTube** button to get to the channel page on YouTube.

In the channels banner at the top, they can have up-to 4 external links. However, these don't work, and instead redirect the user to the home feed of a random Invidious instance.

**Comment by ManeraKai** [comment]
With LibRedirect disabled and even completely removed from the browser, the same thing happens, it's Invidious's fault not LibRedirect.
Try to visit this link while LibRedirect is disabled and see:
https://yewtu.be/redirect?event=channel_banner&redir_token=QUFFLUhqa1dRRXhHT2lYRWQta2w3YWZwSExLYVduZFZld3xBQ3Jtc0tuaDROUlNtZFhiU0xGM19GMmFMQXZFWGlKTktWTlViSW1sWjVrci1QZ3F1VXV0RUxTZ3J2aFk1TEJreENsXzgtMXEwQUtzSVNzR3FTempabVZvVFpITnNWWk5CX0RIR19Rbjhscnp6c1hYMXNoQzhfQQ&q=https%3A%2F%2Ffractaldreamers.bandcamp.com%2F
