### ISSUE TITLE
suggestion: create an automated ping tester page

### ISSUE THREAD

**Issue by cyberhardt** [libredirect/browser_extension#704]
hello. libredirect is a fantastic program, and to be fair its most useful function is the Ping Instances one. It makes everything so much better. I was wondering, if you could make a webpage, either standalone or here on github, that would automatically ping all instances from the frontends and deliver the results on a single page (and list them by milisseconds). ideally it would be an automated process that would go in circles pinging the frontends. you could go even further and make it test the speed on different parts of the world (example: north america, south america, western europe, eastern europe, south africa, middle east, east asia ,central asia, south-east asia, oceania, etc), but even one single test zone would be very useful already.

**Comment by cyberhardt** [comment]
this would be useful not only to users but to those who develop those programs, so that they can better assess the instances and list only those who work properly. as an example, I tested all wikiless instances myself a while ago, because 6 out of ~20 were offline, and made a list out of it so that the dev can remove those that no longer work. a ping tester like that could also help direct the load to instances that can handle it, and then balance it among the best ones, automatically. by adding some more info on the instances such as whether they have cloudfare or not, whether they collect sensitive data or not, etc,  the whole frontend ecosystem could become way more efficient and user friendly.

**Comment by ManeraKai** [comment]
For developers: This project may be interesting to you: [farside](https://github.com/benbusby/farside).
For users and us LibRedirect: We're going to switch to switch to [LibRedirect Frontends Manager](https://github.com/libredirect/frontends_manager) and stop using instances slowly.

**Comment by cyberhardt** [comment]
> For developers: This project may be interesting to you: [farside](https://github.com/benbusby/farside). For users and us LibRedirect: We're going to switch to switch to [LibRedirect Frontends Manager](https://github.com/libredirect/frontends_manager) and stop using instances slowly.

Hm... farside seems interesting, but at first glance I've noticed some issues:

1 - it doesn't tell you the ping, nor list the instances by ping

2 - there seem to be some instances missing, such as imgur.artemislena.eu in the Rimgo list (I've noticed it because it is the one I use). I thought that maybe they ignored instances with high ping, but, taking the rimgo case as an example, there are some low ping instances that were ignored (https://i.habedieeh.re/, https://ri.zzls.xyz/, https://rim.odyssey346.dev/)

3 - there are some frontends missing - gothub, tent, the youtube music ones, breezewiki, anonymous overflow.

4 - it supports bibliogram, which doesn't work for a while now.
