### ISSUE TITLE
suggestion: dim the redirects you are not using on the extension's page

### ISSUE THREAD

**Issue by cyberhardt** [libredirect/browser_extension#705]
as of now, all sites appear equally bright, whether you have their redirects enabled or disabled. I think it would improve usability if the disabled redirects dimmed the sites so that you know they are disabled.

**Comment by ManeraKai** [comment]
This is why for example the "Enable" button is not dimmed, bc it should be the only clickable thing if you have disabled it, but as for the side links, they should be too clickable and not dimmed just like the "Enable" button.

**Comment by cyberhardt** [comment]
> I did it but it now looks so confusing: [1334×946 png138.9 kB![image](https://user-images.githubusercontent.com/40805353/238719304-4ff27852-6526-462a-a31e-1c4eafd82727.png)](https://user-images.githubusercontent.com/40805353/238719304-4ff27852-6526-462a-a31e-1c4eafd82727.png) The user will think it's un-clickable

I honestly think it looks great, it is exactly what I was talking about. While I don't believe users will get confused, you could alternatively put the enable/disable button right on the main UI (with or without the dim), next to the programs' names. That way it would definitely improve usability without confusing a single soul

**Comment by ManeraKai** [comment]
> I honestly think it looks great, it is exactly what I was talking about. While I don't believe users will get confused

We should make votes about this then xD @IkelAtomig

>

**Comment by cyberhardt** [comment]
> We should make votes about this then xD @IkelAtomig

> No no. Let's relook at the first option.

alright

**Comment by ManeraKai** [comment]
Hmm I understood now, you'll understand from this video:

https://github.com/libredirect/browser_extension/assets/40805353/1cff938f-b182-4748-ad01-2b7a82bdcb3b

but now this:

https://github.com/libredirect/browser_extension/assets/40805353/f2071a4b-ed25-4e6a-ae51-8b5d307a374b

but it should also stay popped out when I'm in that page. I'll do that too.

**Comment by cyberhardt** [comment]
> Hmm I understood now, you'll understand from this video:
> 2023-05-18.09-06-29.mp4
> 
> but now this:
> 2023-05-18.09-10-06.mp4
> 
> but it should also stay popped out when I'm in that page. I'll do that too.

Makes sense, looks great

**Comment by ManeraKai** [comment]
https://github.com/libredirect/browser_extension/assets/40805353/97eb904f-abac-447b-96ae-1a6921c6f2f9

:)

**Comment by cyberhardt** [comment]
> 

nice, glad to be of help
