### ISSUE TITLE
Publish extension to Opera add-ons

### ISSUE THREAD

**Issue by xmha97** [libredirect/browser_extension#707]
Hi, please publish this extension to Opera add-ons.
https://addons.opera.com/en/extensions/
(Also Opera can install CRX files using drag and drop without any limitation)

**Comment by ManeraKai** [comment]
I already "tried"...
![image](https://github.com/libredirect/browser_extension/assets/40805353/a5a3b021-fead-4a96-87fe-caa67f6e7153)
but I think we should add an `opera.reg` file for the windows installation
