### ISSUE TITLE
IMDB redirect to domain returning 403 error

### ISSUE THREAD

**Issue by slrslr** [libredirect/browser_extension#709]
I have visited a movie page at https://www.imdb.com and ended up at
https://lmdb.tokhmi.xyz where i seen 403 error.
Next time i ended up at
https://libremdb.esmailelbob.xyz/title/tt123456 where i see "something went wrong (500)".
Then a minute later clicking reviews on movie page brought me to
https://libremdbeu.herokuapp.com/title/tt123456/reviews/ where i see " Application error".
I am using Firefox ESR extension LibRedirect 2.5.4
This experience really sucks big time. Where can i report this please so this may be fixed for everyone?

**Comment by zyachel** [comment]
hey there!
seems like these instances are either down or not being updated.  
I'll ask maintainers for updating them, if possible.  
I'll also remove dead instances.  

thanks for reporting!

**Comment by ManeraKai** [comment]
For more reports, report them in LibreIMDb repo: https://github.com/zyachel/libremdb
