### ISSUE TITLE
feature request: ping instances in the background every 5-15 min for temp disabling them

### ISSUE THREAD

**Issue by su-klubert** [libredirect/browser_extension#710]
feature request: ping instances in the background every 5-15 min for temp disabling them if they are offline

i like to use more than just a few instances and even if i do just use a few, some of them may go offline for a short time and i dont want to remove and than readd them.

example: https://libreddit.hu just went down or my dns blocks it - i dont use reddit a lot but i sometimes want to quickly check due to search engine results and it sucks when i get a dead page. 

lmao just realized its my family filter dns which blocks reddit sites :D most likely for the best, but i happened before where i for a long time dont use websites that front end others than want to use it and then the instances went down. 

it would be very kind if you can preform a background check of the favorite instances the user selected and preform a frequently ping to these instances in order to check if the are ready for use and if not then temporarily disable them for (30 min or so).

goal: have 99% of the time an instance that just works when redirecting

**Comment by ManeraKai** [comment]
We'll fix this problem from the ground up: https://github.com/libredirect/frontends_manager

**Comment by su-klubert** [comment]
im hosting some Frontends but i  doubt my mom can do the same.

**Comment by ManeraKai** [comment]
Frontends Manager is exactly intended for your mom, something that is simple to use.

**Comment by su-klubert** [comment]
nono you dont get it, im happy that she is capable of opening the browser.
no matter how easy you make it, non tech users wont go through the hassle because they dont care enough. thats why i setup the instances, people can use it if they want to. so i can install my mom a browser extension and she does not have to worry at all. if instances break she is pissed at me for a valid reason, if i than tell her to download and execute something i guess she would just shutdown the computer and tell me to do this.... i hate to be tech support

**Comment by ManeraKai** [comment]
I dearly understand... Giving privacy to people whoa aren't techies is near impossible and they just need on a straw to quit.

Frontends Manager is still under development but I'll make it as automatic as possible with the browser extension. We decided to go to this path we will start not supporting instances slowly.

**Comment by ManeraKai** [comment]
I'm closing the issue

**Comment by su-klubert** [comment]
> We decided to go to this path we will start not supporting instances slowly.

Sad to see a good extension die. Instances proxy requests for many people, most instances like mine have logs redirected to /dev/null or other reasonable logging settings. If you force people to host their own frontends than people cant proxy (in term of obfuscating) their requests so they are in most cases less private if the user is not obfuscating the hole network traffic.

**Comment by ManeraKai** [comment]
Trusting a random instance not logging your traffic is a really bad thread model. That's why I recommend Lokinet for proxying the traffic. With Lokinet the instances will see just encrypted data let alone log my watching history.

Hosting the frontend locally improves privacy more by having the frontend (HTML/CSS/JavaScript) saved locally with all your "custom settings" rather than being saved as cookies or as accounts on instances.

**Comment by su-klubert** [comment]
you do you. i never said its a bad idea to make local frontends easier available, i said denying users to use hosted frontends efficiently is retarded. 

i dont care if a random instance is logging my traffic as long as its not stored with big data tech companies.
i dont want to start a big discussion about it. we saw it with freetubes local instance usage sucks if the website you frontend hacks around alot to break the frontends. invidious instance for example would get kicked out of the public instance list if they add malicious stuff. so yeah it may be the case"malicious tracking scripts" is around 80% of the web...

**Comment by ManeraKai** [comment]
> i said denying users to use hosted frontends efficiently is retarded.

No the option would still be there, but I won't add additional features to it like this issue.

**Comment by su-klubert** [comment]
> We decided to go to this path we will start not supporting instances slowly.

Okay sorry than i miss understood this statement. I understand that change but just so you know i donated to this project back in the day when it still had crypto addresses linked for the intent of using it for the use with hosted instances. As long as your self hosted instances are well sandboxed and frequently updated i guess it wont be an issue. I have seen it now for over 2 years where freetube keeps being shit, i reported issues they claimed to be fixed in next release which are still present after years... from simple design flaws to basic functionality. i guess thats why i was quite pissed when i thought you wanted to remove hosted instances after some time completely. removing options and forcing everyone to change is a highway to lose users who were early adopters and most likely promoters. (i dont say those are more right / important than the current user base)

**Comment by su-klubert** [comment]
@ManeraKai just realized you removed the ability to use librarian (lbry) instances and i now need to install the desktop app which sucks af. 
why you force such changes? its one of the few redirects i used frequently
