### ISSUE TITLE
Add Destructables (Instructables)

### ISSUE THREAD

**Issue by fd1f** [libredirect/browser_extension#711]
The developer asked me to. The source code for Destructables can be found at https://git.vern.cc/cobra/destructables.

Currently the only instance is [ds.vern.cc](https://ds.vern.cc).

**Comment by ManeraKai** [comment]
The Contests page is working, and the Contest page is too.
The Projects page is working, but the single Project page is not.
The Teachers page is working, but the single Teacher page is not.
All the others aren't working, and the repo hasn't been updated from the past 4 months. What do you think?

**Comment by ManeraKai** [comment]
I won't add it, but tell me of any updates.

**Comment by jermanuts** [comment]
> I won't add it, but tell me of any updates.

Looks like every page is functioning well and is actively maintained.

**Comment by ManeraKai** [comment]
oh I remember there was a debate (https://codeberg.org/LibRedirect/browser_extension/issues/97). We already added it.
