### ISSUE TITLE
Won't install in Edge Dev

### ISSUE THREAD

**Issue by bgiesing** [libredirect/browser_extension#712]
I followed the instructions on the site including installing the edge.reg file and even restarting my whole PC, not just the browser and it still blocks installation of the extension with the error "This extension is not from any known source, and may have been added without your knowledge."

Edge version: 115.0.1851.0

**Comment by ManeraKai** [comment]
I think bc there's a difference between the registry for normal edge and edge dev, but in theory there should be a settings to disable the "requirement of signature" bc this is a "dev version". I will see.

**Comment by ManeraKai** [comment]
I have just tried now, using edge.reg is suitable for both Edge and Edge Dev. Plz follow the video carefully, try again and tell me.
