### ISSUE TITLE
[2.6.0] Fix Frontend when removed

### ISSUE THREAD

**Issue by IntinteDAO** [libredirect/browser_extension#713]
It could be a problem just with me, although probably unlikely. After updating libRedirect the plugin worked, but no redirects worked. I checked that there was a libRedirect update yesterday and Librarian was removed.

Setting up LBRY Desktop made the redirects work.

There is probably a bug in the code that disables all redirects if there is an erroneous redirect. It would be good to correct this so that there are no errors in the future.

This problem occurs on Firefox.

**Comment by krystian3w** [comment]
https://github.com/libredirect/browser_extension/issues/714
