### ISSUE TITLE
SimplyTranslate redirect no longer works

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/browser_extension#714]
Despite having Google Translate redirects enabled:

![translateinstance](https://github.com/libredirect/browser_extension/assets/1284317/799278a7-3478-45aa-aeaf-6cd2e2b942f6)

if I go to `https://translate.google.com/` it takes me to Google Translate, not any of the SimplyTranslate instances I have selected. I think this broke in 2.6.0. (Changing `bypass` to `block` has no effect.)

Edit: I'm running Chrome v113

**Comment by ManeraKai** [comment]
Is this happening with any other frontend? with me it's working completely fine weird. I need more details.

**Comment by AlyoshaVasilieva** [comment]
All other frontends I use work fine.

Something seems to be wrong with LR's settings. After resetting my settings then enabling SimplyTranslate it works, when importing the old settings it breaks. I can't figure out what in my settings is causing this. I'll see if I can clean the json up to remove mention of my private instance and post it

**Comment by AlyoshaVasilieva** [comment]
My settings contained LBRY enabled and set to Librarian, as such:

```json
  "lbry": {
    "enabled": true,
    "frontend": "librarian",
    "redirectType": "both",
    "unsupportedUrls": "bypass"
  },
```

This option no longer exists in 2.6.0.

 Editing them to instead contain

```json
  "lbry": {
    "enabled": false,
    "frontend": "lbryDesktop",
    "redirectType": "main_frame",
    "unsupportedUrls": "bypass"
  },
```

then importing them fixed the broken redirect of SimplyTranslate.

Importing the unedited settings that refer to librarian cause devtools to spam 

```
Error in event handler: TypeError: Cannot use 'in' operator to search for 'excludeTargets' in undefined
    at regexArray (<URL>)
    at Object.redirect (<URL>)
    at browser.webRequest.onBeforeRequest.addListener.urls (<URL>)
    at subEventCallback (extensions::webRequestEvent:106:32)
```

Importing the fixed settings does display a couple instances of

```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'exceptions')
    at Object.isException (chrome-extension://oladmjdebphlnjjcnomfhhbfdldiimaf/assets/javascripts/services.js:844:27)
    at browser.webRequest.onBeforeRequest.addListener.urls (chrome-extension://oladmjdebphlnjjcnomfhhbfdldiimaf/pages/background/background.js:48:22)
    at subEventCallback (extensions::webRequestEvent:106:32)
```

but I can't find anything broken.

If I had to guess, it's trying to read librarian's settings, erroring out, and then not loading anything below LBRY (like Translate is)

**Comment by ManeraKai** [comment]
This bug crashes all the frontends after LBRY apparently.
