### ISSUE TITLE
Let users add a custom URL to match for various front ends

### ISSUE THREAD

**Issue by amogusussy** [libredirect/browser_extension#715]
Please add a feature that lets people add custom URLs to redirect. 
I use librex, and on some instances (search.madreyk.xyz), the admins replace wikipedia links with wikiless.org, which has a messed up UI.
The feature would allow the user to input a custom URL to match. So instead of just matching wikipedia.org, it also matches wikiless.org, or whatever other sites the user wants to redirect.

**Comment by ManeraKai** [comment]
That is a really niche case. I suggest you use [Redirector](https://einaregilsson.com/redirector/) for this case.
