### ISSUE TITLE
[Bug] Libre-search function doesn't work & weird prompt in the toolbar

### ISSUE THREAD

**Issue by darlopvil** [libredirect/browser_extension#716]
Hello guys,

Well, this is kind of bizarre but, after upgrading to the newest version (2.6.0), there are 2 things that don't work as they were before.

First one is the fantastic search option indexed among others search engines in the search toolbar. It just doesn't work:

![imagen](https://github.com/libredirect/browser_extension/assets/60988792/fa73ee8d-68fe-4c45-a5bc-dea208181b19)
![imagen](https://github.com/libredirect/browser_extension/assets/60988792/7bcde287-89e1-4b76-8ca2-da2bfa43c522)

It's in spanish but i think you guys know what it means...

Second weird thing happening is when accessing to the add-on, clicking in the icon fixed in the addon's toolbar. There's only 2 options available, when I've enabled most of them:
![imagen](https://github.com/libredirect/browser_extension/assets/60988792/ba920243-3fcd-4f83-be9f-74ef5e9ef9f5)

Specs:
-Browser used: LibreWolf
-2nd browser checked: Ungoogled Chromium (both problems persist)

I apologize for my bad use of the language, clearly English is not my native language.

**Comment by ManeraKai** [comment]
You were using Librarian right?

**Comment by darlopvil** [comment]
You mean LBRY, right?

I thought it was activated (like the rest of the frontends), but when I went to the options page, it appeared deactivated. I have re-enabled it but there seems to be no instances...

![imagen](https://github.com/libredirect/browser_extension/assets/60988792/f559b1eb-b808-4b9e-99b6-8024bd805fad)

i'm missing something?

**Comment by ManeraKai** [comment]
See this bug: https://github.com/libredirect/browser_extension/issues/713 that happenned bc we removed a frontend (Librarian in this case). [LBRY Desktop](https://lbry.com/get) is a Desktop App it doesn't need instances.

**Comment by darlopvil** [comment]
Sorry for the misunderstanding. I thought that issue was another thing completely different. I'm truly sorry.

I'll be waiting for more updates then. Hope you guys continue this project 🙏

**Comment by ManeraKai** [comment]
Will then be completed here https://github.com/libredirect/browser_extension/issues/713.

**Comment by darlopvil** [comment]
Re-open this issue since this latest version 2.6.2 still didn't fix the addon pop-up window in the toolbar.

![imagen](https://github.com/libredirect/browser_extension/assets/60988792/e82de0d3-fa21-4a83-b0d1-e91ad124dfb4)

Now this new option call "Redirect" appears as new I guess, but only Youtube and Twitter seem to work as shown

**Comment by ManeraKai** [comment]
Have you tried resetting your settings? Or is this problem bc of your language option??

**Comment by darlopvil** [comment]
> Have you tried resetting your settings (backup before doing that)?

Done. Problem persists.

>  Or is this problem bc of your language option??

Tried it on a fresh profile in LibreWolf (english by default) and the problem persists.

**Comment by ManeraKai** [comment]
On what tab you opened the popup? bc it changes according to the current tab url.

**Comment by darlopvil** [comment]
It's always the same 2 options.

I've tried so far: browser option page, new tab page, this page itself, etc.

**Comment by ManeraKai** [comment]
I hate no idea what's going wrong. Let's see if this is happening to any other user.

**Comment by darlopvil** [comment]
I hope so, in the meantime I've back to defaults and applied the config I had manually. Now it works everything smoothly.
