### ISSUE TITLE
[Question] Is it possible to add extension to android WebView browsers?

### ISSUE THREAD

**Issue by Taratect** [libredirect/browser_extension#717]
Hi, I'm currently using a browser called Via made using Android WebView
https://github.com/tuyafeng/Via

In this browser, there is a option to add your own add ons by JavaScript. Welp I'm pretty new to programming. So I was wondering if a libredirect extension can be made more WebView browsers?

There are various WebView browsers out there, it'd be nice to add the functionality of redirecting to privacy friendly frontends.

**Comment by ManeraKai** [comment]
This should be followed up here: https://github.com/tuyafeng/Via/issues/1318, apparently till now Via didn't implement it.
