### ISSUE TITLE
Youtube redirect settings acting weird

### ISSUE THREAD

**Issue by MF-Debug** [libredirect/browser_extension#718]
After latest update (2.6.1), I'm facing weird issue for youtube redirection. The settings page doesn't load any instances. Even if I enabled it, the JSON file says it is not enabled. Also, There's no redirect type as well. I tried reset settings but no luck. I uninstalled the extension and reinstalled it but the issue remains.
![image](https://github.com/libredirect/browser_extension/assets/6173607/11288c94-4826-4fb5-91a8-6a02e43a5559)

I'm using latest firefox nightly 64-bit build. Here's my JSON file.
[libredirect-settings-v2.6.1.txt](https://github.com/libredirect/browser_extension/files/11566759/libredirect-settings-v2.6.1.txt)

**Comment by ManeraKai** [comment]
I already released a [hotfix](https://github.com/libredirect/browser_extension/releases/tag/v2.6.2) for this just upgrade to 2.6.2.

**Comment by MF-Debug** [comment]
Thanks, it is fixed now. But the same issue is now happening for Send Files settings.
![image](https://github.com/libredirect/browser_extension/assets/6173607/72ccae2d-f91d-4a2a-b2d0-d62c796621c1)

**Comment by ManeraKai** [comment]
This is another issue specifically here: https://github.com/libredirect/instances/blob/main/instances.py#L296
Fixing it...

**Comment by ManeraKai** [comment]
Check your settings now :)
