### ISSUE TITLE
An easier way to enable this on ChromeOS.

### ISSUE THREAD

**Issue by SecularSteve** [libredirect/browser_extension#720]
That is, the Chrome Browser on it (not counting Firefox).

Not only are there no options to enable this without force-enabling Developer Mode on a Chromebook, but there are no instructions as well.

It's a good extension. It would be a shame to dev-lock it for ChromeOS devices.

**Comment by ManeraKai** [comment]
ChromeOS is linux, have you tried linux way of installing?

**Comment by ManeraKai** [comment]
ChromeOS is linux, so the instructions are there (I think I will add ChromeOS).
About dev-lock, bc LibRedirect is not in the chrome web store, it's unverified so if the device was dev-locked, we can't do anything about it.

**Comment by SecularSteve** [comment]
It's not that simple. If it was I wouldn't be making this.

I can't download the .CRX unless I enable the OS Developer Mode (not the browser).

Every time I try downloading it, even while bypassing the warning, it gets automatically erased anyway due to the strict built in antivirus.

No other way to use it on ChromeOS, and the OS Developer Mode severely limits your right to update the browser.

**Comment by ManeraKai** [comment]
I can't do anything about this sadly, even the "Windows way" was the most complex one to let the browsers allow me to install LibRedirect, I still needed to enable developer mode. All of this is bc LibRedirect isn't in the chrome web store (untrusted), and btw this is [why](https://libredirect.github.io/faq.html#chrome_web_store).

**Comment by SecularSteve** [comment]
No worries.
I'm glad you've answered my questions at the very least.
It's okay. I understand.
