### ISSUE TITLE
Redirect paths on Wayback Classic

### ISSUE THREAD

**Issue by ndren** [libredirect/browser_extension#721]
The wayback machine uses the URL path to get the correct page shown.

Although it may not possible to fully parse this, it would be nice if it could get the final part of the URL and redirect that:

https://web.archive.org/web/20230524224706/https://libredirect.github.io/ -> https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/&utf8=✓

Similarly, https://web.archive.org/*/https://libredirect.github.io/ -> https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/&utf8=✓

I think `/(https?.*$)` would work fine here, and then appended to `$INSTANCE_URL/cgi-bin/history.cgi?q=` with `&utf8=✓` at the end.

Thanks!

**Comment by ndren** [comment]
Actually, even better, there's no need to URL encode! https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/ works fine.

**Comment by ndren** [comment]
I think I stripped out too much, the site is only happy with https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/&utf8=✓

Please use that instead, with the utf8 parameter set.

**Comment by ManeraKai** [comment]
> https://web.archive.org/web/20230524224706/https://libredirect.github.io/ -> [https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/&utf8=✓](https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/&utf8=%E2%9C%93)

This should be like this:
https://web.archive.org/web/20230524224706/https://libredirect.github.io/ => https://web.archive.org/web/20230524224706if_/https://libredirect.github.io/

No no, it should go to The Wayback Machine directly. Wayback classic just injects that `if_` to remove the upper info bar apparently from The Wayback Machine. I think I should make LibRedirect do this internally (for old browsers).

> Similarly, https://web.archive.org/*/https://libredirect.github.io/ -> [https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/&utf8=✓](https://wayback-classic.net/cgi-bin/history.cgi?q=https://libredirect.github.io/&utf8=%E2%9C%93)

Alright will add this.

**Comment by ManeraKai** [comment]
I really think though wayback classic is out of the scope of LibRedirect, just like old reddit's case: https://libredirect.github.io/faq.html#suggest_frontend

**Comment by ManeraKai** [comment]
Nah I won't, his [point](https://github.com/libredirect/browser_extension/issues/578#issuecomment-1420652516) makes sense.
