### ISSUE TITLE
New Frontend: Laboratory: GitLab Frontend

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#723]
Source: https://git.vitali64.duckdns.org/utils/laboratory.git/about/

**Comment by ManeraKai** [comment]
Just keep in mind about the last slash:

- https://lab.vern.cc/gitlab.com working
- https://lab.vern.cc/gitlab.com/ not working

- https://lab.vern.cc/gitlab.com/BETAIDK/simple-warp/ working
- https://lab.vern.cc/gitlab.com/BETAIDK/simple-warp not working

And thanks for mentioning the frontend :)
