### ISSUE TITLE
New Frontend: eddrit: Reddit Frontend

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#724]
Source: https://github.com/corenting/eddrit

**Comment by xbdmHQ** [comment]
Tested, it is broken and doesn't have proxy. Just no ads/javascript.

**Comment by ManeraKai** [comment]
It could be still under development though. I'm gonna close this issue till it change or progress

**Comment by drakeerv** [comment]
It looks like this is now working. Would you reconsider adding this?
![image](https://github.com/libredirect/browser_extension/assets/60192521/b07fe5aa-2d6c-48f7-98db-79029c653994)
