### ISSUE TITLE
New Frontend: ReQuiz: An alternative frontend for Quizlet.

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#726]
Website: https://requiz.net/

Example: https://requiz.net/270110174/german-verbs-flash-cards/

**Comment by ManeraKai** [comment]
Where is the source code? The example is broken too.

**Comment by xbdmHQ** [comment]
> Where is the source code? The example is broken too.

Seem like the guy made a frontend and closed-source it, but seems to not have any trackers/ads when i checked the site and i found the frontend by going to reddit

**Comment by drakeerv** [comment]
I might make a FOSS frontend for quizlet later.
