### ISSUE TITLE
New Frontend: omgur: Reddit Frontend

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#727]
Source: https://gitlab.wuhoo.xyz/jerry/omgur

**Comment by ManeraKai** [comment]
![image](https://github.com/libredirect/browser_extension/assets/40805353/7e6da5ad-9858-470b-9b6f-f35f2d6aa494)
Nope

**Comment by xbdmHQ** [comment]
Shit my bad I'm high lol
