### ISSUE TITLE
Feature Request: List of Onion instances

### ISSUE THREAD

**Issue by ss11mik** [libredirect/browser_extension#731]
When using LibRedirect in Tor Browser, some instances get redirected to their onion address, which is not in DB of the plugin and hence the menu with "switch instance" etc. is not available.

Also upon redirection to onion address, (some) Invidious instances redirect to home page, even if original address was of a video or so. But this is probably a bug of Invidious.

I think a separate list of instances for Tor Browser would solve this, though I am aware it might not be worth the effort. So I'm rather issuing this for sake of completeness than "demanding" a fix.

**Comment by ManeraKai** [comment]
> I think a separate list of instances for Tor Browser would solve this

Tor instance are already there in the list (at the bottom)? but the thing is even if they are, if they are not in your favorite list, they won't be recognized as instances. Same thing goes to any other instance url even clearnet.
