### ISSUE TITLE
Bug: Plugin is unaware of current tab

### ISSUE THREAD

**Issue by ss11mik** [libredirect/browser_extension#732]
Version: 2.6.2
Browser: Firefox

Steps to reproduce:
- open a redirected website.
- open plugin menu. Options "Switch Instance", "Copy Original" and "Redirect To Original" should be visible.
- switch to another browser tab without closing the plugin menu, e.g. by Ctrl+PageUp. Whether the next tab is currently on recognized instance or not does not seem to have effect.
- click on one of the options. The action happens in current tab, but with context (address) of the tab where the menu was opened.

Expected behaviour:
The menu should display and perform actions relevant to current tab.

**Comment by ManeraKai** [comment]
The popup menu isn't updating when a tab is switched that's why, it only processes information when you open it. idk if this is necessary though.
