### ISSUE TITLE
SearXNG switch instance: page not found

### ISSUE THREAD

**Issue by cyber-bytes12** [libredirect/browser_extension#733]
When switching from an instance with a /search/ or /searx/ etc after the domain to another instance using the "switch instance" button, you are greeted with a page not found error. 

Steps to reproduce:
1) Go to https://searxng.nicfab.eu/searxng/search?q=hello+world
2) Click "Switch Instance" in the plugin options

Proposed Fix:
Remove everything before the /search?q= parameter in the URL before generating the new URL.

**Comment by xbdmHQ** [comment]
> When switching from an instance with a /search/ or /searx/ etc after the domain to another instance using the "switch instance" button, you are greeted with a page not found error.
> 
> Steps to reproduce:
> 
> 1. Go to https://searxng.nicfab.eu/searxng/search?q=hello+world
> 2. Click "Switch Instance" in the plugin options
> 
> Proposed Fix: Remove everything before the /search?q= parameter in the URL before generating the new URL.

https://search.whateveritworks.org - try mines

**Comment by ManeraKai** [comment]
>  Remove everything before the /search?q= parameter in the URL before generating the new URL.

Then how will you know if an instance is using an additional path?
Example: https://example.com/search?q=hello+world => https://example.eu/searxng/search?q=hello+world
It's a 50% chance, I can't choose one over the other.
