### ISSUE TITLE
`Show in popup` doesn't work

### ISSUE THREAD

**Issue by ccuser44** [libredirect/browser_extension#739]
Even if I turn the `Show in popup` option on for all instances they still don't show up.

None of the instances show in the toolbar popup regardeless of `Show in popup`.

Image:
![image](https://github.com/libredirect/browser_extension/assets/68124053/b8820413-ae22-4f0f-b510-6a6dca665e72)

**Comment by ManeraKai** [comment]
I'm not completely sure, it could be bc of us removing Librarian and it messed up the settings.
