### ISSUE TITLE
LibRedirect disappearing from Brave

### ISSUE THREAD

**Issue by Oppen** [libredirect/browser_extension#741]
Running on MacOS Ventura 13.4 on Apple Silicon. I'm pretty sure the issue is not in the extension itself, but I feel luckier asking here than to Brave support.
I noticed that twice already libredirect stopped working and that the extension is actually not installed anymore. I've been using it for months without issue. I find out it's not there whenever I open some Twitter or Reddit link to find it opens the regular site.
Did this happen to anybody? Clues for debugging it? I'm quite annoyed at this. Is it possible Brave is blacklisting something?

**Comment by Oppen** [comment]
Hold up. Does the browser copy unpacked extensions somewhere? I think maybe because I deleted the folder in Downloads it's deleting the extension. I would have expected to __copy the contents__ to its own, but maybe that's not how it works?

**Comment by ManeraKai** [comment]
https://github.com/libredirect/browser_extension/issues/687#issuecomment-1532051667

**Comment by ManeraKai** [comment]
> Hold up. Does the browser copy unpacked extensions somewhere? I think maybe because I deleted the folder in Downloads it's deleting the extension. I would have expected to copy the contents to its own, but maybe that's not how it works?

Exactly, bc it's in debug mode this happens.
