### ISSUE TITLE
TOR usage question - Safe to use?

### ISSUE THREAD

**Issue by NearestWater262** [libredirect/browser_extension#744]
Hello, thank you so much for making a wonderful extension! it is extremely useful

I have one question - is this safe to use on TOR browser? I know that everyone says to not use extensions in TOR, but this extension has onion addresses.

Is this because it does not alter the Document Object Model in any way therefore undetectable by the website?

is there any possible way that a browser extension can be detected, regardless of this??

Thanks for your input and have a wonderful week.

**Comment by xbdmHQ** [comment]
> Hello, thank you so much for making a wonderful extension! it is extremely useful
> 
> I have one question - is this safe to use on TOR browser? I know that everyone says to not use extensions in TOR, but this extension has onion addresses.
> 
> Is this because it does not alter the Document Object Model in any way therefore undetectable by the website?
> 
> is there any possible way that a browser extension can be detected, regardless of this??
> 
> Thanks for your input and have a wonderful week.

Yes, this extension works fine in the tor browser. Just don't install anything else.

**Comment by ManeraKai** [comment]
- if you injected a script in a webpage, that would be detected (LibRedirect doesn't do that).
- If you also redirected Embeds, then they can be a fingerprint (that's why they are disabled by default).

> Is this because it does not alter the Document Object Model in any way therefore undetectable by the website?

Exactly

**Comment by ManeraKai** [comment]
> is there any possible way that a browser extension can be detected, regardless of this??

As far as I know I don't think so.

**Comment by NearestWater262** [comment]
@xbdmHQ @ManeraKai thank you very much for these assurance
