### ISSUE TITLE
Right-click menu missing for YouTube videos

### ISSUE THREAD

**Issue by raisedintheusa** [libredirect/browser_extension#745]
A right-click menu item for Libredirect used to appear when right-clicking on the image of videos on YouTube, but has recently disappeared. The Libredirect menu item still appears when right-clicking on the title of the video.

**Comment by ManeraKai** [comment]
I suppose you are on windows, it's a weird thing, even if I clicked the middle mouse button, it doesn't open in a new tab unless I middle mouse click on the title of the video. This issue isn't related with LibRedirect.

**Comment by raisedintheusa** [comment]
I'm on Linux and strangely just right now it began to work again.
