### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#747]
![](https://bffr.wtf/r/DxSuZ9.jpg?compress=true)

**Comment by ManeraKai** [comment]
Read the [Development](https://github.com/libredirect/browser_extension#development), you should first generate the html files.

**Comment by xbdmHQ** [comment]
> Read the [Development](https://github.com/libredirect/browser_extension#development), you should first generate the html files.

oh shit my fault
