### ISSUE TITLE
Settings page has off-screen controls on smaller screens

### ISSUE THREAD

**Issue by ISSOtm** [libredirect/browser_extension#748]
I have two Firefox windows each talking one (horizontal) half of my monitor, and unfortunately I thought the Settings page was broken at first:

![Settings page screenshot](https://github.com/libredirect/browser_extension/assets/15271137/c20ffee9-79cf-497e-ae6d-f6621bda376a)

...but making the window full-screen "fixed" that issue. It would still be nice not to need to do that, though.

**Comment by ManeraKai** [comment]
It's like this now:
![image](https://github.com/libredirect/browser_extension/assets/40805353/befec3f4-1947-4aa5-9a1c-2d7e7f9e7a04)
