### ISSUE TITLE
Add client-side encryption in the browser redirection [hat.sh]

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#749]
https://hat.sh
https://github.com/sh-dv/hat.sh

**Comment by njmdietrich** [comment]
What is your suggestion here, exactly?

**Comment by IkelAtomig** [comment]
It's a tool and already Open source. Anybody could access it. If you say that it is a way of promoting it. Then suggest a Proprietary one which is popular and acts an alternative to it.

**Comment by xbdmHQ** [comment]
> What is your suggestion here, exactly?

Sense they added “Send”, thought they could redirect all proprietary client-side encryption in the browser to hat.sh, that's all.

**Comment by IkelAtomig** [comment]
Send was added because to redirect from the dead project send.firefox.com to their Forks. Which is a file sharing service.

While hat.sh is a Encryption tool that runs in the browser. See the 'Difference'.
