### ISSUE TITLE
Add Bibliogram Instagram Frontend

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#751]
https://www.picnob.com/

**Comment by ManeraKai** [comment]
This is not bibliogram.

**Comment by xbdmHQ** [comment]
> This is not bibliogram.

Yes, it is. Everyone knows about it. Whoever it is edited the source code, and now we got an Instagram frontend, It just closed source but better than nothing.

**Comment by ManeraKai** [comment]
See this: https://github.com/libredirect/browser_extension/issues/573
