### ISSUE TITLE
Twitter broke everything? Tweet not found. Error in user page

### ISSUE THREAD

**Issue by fadelkon** [libredirect/browser_extension#753]
Hi, has Twitter broken anything? I haven't been able this week to see any tweet or user account, I think it's generalised. I also tried with some private code twitter viewer and it's broken too.

When visiting a twitter account (e.g. @La_Directa )
https://nitter.kylrth.com/LaDirecta/
```
An error has occured in one of your routes.

Detail: jsony.nim(45) parseHook
asyncfutures.nim(389) read
redpool.nim(68) getUserIdIter
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
Expected { but end reached. At offset: 0
```

If we try to visit some tweet, it says "tweet not found". I can't show you any real example but you get it.

Probably this announcement is the reason behind the problem
June 30, 2023 https://mashable.com/article/twitter-force-visitors-login-view-tweets-profiles
> Twitter now blocks visitors from viewing tweets, and profiles unless they're logged in
> Elon Musk continues to limit how the platform can be accessed.

**Comment by ManeraKai** [comment]
Migrate the issue to [nitter](https://github.com/zedeus/nitter/issues)
