### ISSUE TITLE
Redirecting from HTTPS to HTTP often doesn't work

### ISSUE THREAD

**Issue by gBasil** [libredirect/browser_extension#755]
When redirecting from an HTTPS site, say YouTube, to an HTTP site, say a local Invidious instance (with a local DNS server with a non-standard TLD), the redirect sometimes never happens and it seems to load indefinitely..

**Comment by ManeraKai** [comment]
Is HTTPS-ONLY enabled in your browser?

**Comment by ManeraKai** [comment]
In LibRedirect it doesn't matter what the link is https or http, nor it the TLD matters. I think it's a browser cache problem. Check on another browser or try visiting your instance without using LibRedirect and see.

**Comment by ManeraKai** [comment]
I checked the code, your problem has nothing to do with LibRedirect. We don't prioritize `https` or `http` or even if you used a different protocol (ex: `freetube://`) it's not a problem. This is probably bc of your custom setup.
