### ISSUE TITLE
Redirect Fediverse links to a specific instance

### ISSUE THREAD

**Issue by njmdietrich** [libredirect/browser_extension#756]
This is a somewhat different concept to the libredirect features so far, but it would be immensely useful.
The issue with the Fediverse (mastodon, lemmy, etc) is that if you want to engage with content from another instance, you first have to copy the link and paste it in your current instance to be redirected to a version of that content on your instance. Shouldn't it be possible to pull a list of e.g. mastodon instances, let the user select their home instance, and redirect all links from other instances to that content on the home instance?

**Comment by IkelAtomig** [comment]
Instead of integrating this idea into Libredirect, There is a separate extension in works just for Fediverse.

**Comment by njmdietrich** [comment]
Awesome! Can we follow the progress somewhere?

**Comment by ManeraKai** [comment]
Heh I think now it's the time to SHINE: [FediRedirect](https://github.com/ManeraKai/fediredirect)!
