### ISSUE TITLE
Error message loading in Chromium (non-fatal)

### ISSUE THREAD

**Issue by ktleary** [libredirect/browser_extension#758]
When loading the extension v2.5.4 into ungoogled chromium on MacOS, an errors button appeared next to details button in extensions manager. The extension still works and it could be particular to ungoogled, but just a heads up in case it affects anything down the road. 

![image](https://github.com/libredirect/browser_extension/assets/26344840/95238c45-fe9d-4661-a9f8-0dac92b380b2)

**Comment by ManeraKai** [comment]
Is it still happening in the v2.7.0?
