### ISSUE TITLE
Addon doesn't work in Firefox 68

### ISSUE THREAD

**Issue by Anonymous1157** [libredirect/browser_extension#759]
Hi! I tried using the Firefox addon on a legacy platform where the newest possible version of Firefox is 68, and it doesn't work.

I'm able to install the latest version from the Mozilla addons website, and I get a toolbar icon. When I open libredirect's menu, instead of getting the list of toggles, I only see the Settings option, and clicking on it doesn't do anything. I tried installing older versions of the addon and none of them work as far back as 1.7.0; I don't think old Firefox was ever working and I might be the first person to have ever tried.

In the Browser Console, when I open the libredirect menu I get...
```
init.js:7:6 SyntaxError: await is a reserved identifier
popup.js:13:15 SyntaxError: await is a reserved identifier
```

I don't know JS and everything I know is from five minutes of web searching, but what I *think* is happening is that these are top-level `await` calls, support for which was only added in Firefox 89 according to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility

Looks like there's two possible solutions:
- If libredirect really did mean to support Firefox this old, refactor the code to remove top-level `await` calls or move them into async functions
- Bump the minimum requirement to Firefox 89

**Comment by Tallefer** [comment]
@Anonymous1157 
> Hi! I tried using the Firefox addon on a legacy platform where the newest possible version of Firefox is 68, and it doesn't work.

I don't remember the exact version of Firefox, but it was comparably old. I commented in the year-old similar issue here https://github.com/libredirect/browser_extension/issues/117#issuecomment-1077015909
> I'm able to install the latest version from the Mozilla addons website, and I get a toolbar icon. When I open libredirect's menu, instead of getting the list of toggles, I only see the Settings option, and clicking on it doesn't do anything. I tried installing older versions of the addon and none of them work as far back as 1.7.0; I don't think old Firefox was ever working and I might be the first person to have ever tried.

so you may try older versions if you can, or edit either 1.6.3 or 1.7.0 - I made them work for me until I was able to update to later versions :)
