### ISSUE TITLE
Add alternatives for Twitch

### ISSUE THREAD

**Issue by VictorFeroli** [libredirect/browser_extension#760]
I recently found these two alternatives to Twitch:
Source: https://codeberg.org/dragongoose/safetwitch
and
Source: https://codeberg.org/CloudyyUw/twineo

**Comment by dragongooses** [comment]
[All good now :+1:](https://codeberg.org/dragongoose/safetwitch/releases/tag/v2.1.0)

**Comment by ManeraKai** [comment]
Thanks for making this frontend :)
