### ISSUE TITLE
Redirect from known disabled instances

### ISSUE THREAD

**Issue by malimach** [libredirect/browser_extension#762]
Alternative frontend instances can (and do) often break or go offline, and when they do they can be disabled in the extension settings, but then all old links saved in e.g. browser history or bookmarks are permanently broken. It would be useful to have an option to also redirect links from disabled instances to the currently enabled ones.

**Comment by ManeraKai** [comment]
If an instance went offline, then there's no way to know that is "was" an invidious instance. Unless you have a big archive database of what instances went were before.
The solution to this problem is to bookmark the original links, example: bookmark youtube links not invidious links.

**Comment by Tallefer** [comment]
@malimach if you just want to use the "broken" history in a normal way, you can install any other addon that allows custom user redirects, like `Redirector`, and use that until all broken links are fixed.
But if you need to actually edit the history, that's a tough one. You still have some options though! 
You either look for an addon that does exactly that - replaces urls in history (sorry, can't remember the title); unfortunately, it's very old and most probably won't work in a modern Firefox. 
Or, you use a more general addon, like `SQLite Manager` and fiddle with it - probably the most safe option. 
Or, you can edit the places.sqlite file directly, either from the console with the `sqlite3` utility, or use any GUI tool for that.

**Comment by ManeraKai** [comment]
> Ok, great, but why not implement this feature in LibRedirect to make it seamless and automatic?

bc of how much complex it is as @Tallefer said, and it's a really niche use case.
