### ISSUE TITLE
Invidious and shared Youtu.be links

### ISSUE THREAD

**Issue by hermann-san** [libredirect/browser_extension#763]
Hi,
When I receive a shared **youtu.be** link , like https://youtu.be/tI8rlHo832g
It won't be properly redirected to the video via Invidious instances / frontend.
The video won't open, but instead the link get's redirected to the popular youtube feed
It would be great if you could have a look into this.
Thanks.

**Comment by ManeraKai** [comment]
It's probably bc of instances, we can't fetch more information from a shortened link it's invidious' problem.

**Comment by schklom** [comment]
For what it is worth, I just tried https://invidious.privacydev.net and it does not redirect correctly. I also tried with my private instance using the latest Docker image, and it does not work either.

**Comment by hermann-san** [comment]
There is this issue here that indicates a possible bug in Invidiuos.
https://github.com/iv-org/invidious/issues/3933

**Comment by rezad1393** [comment]
could this be worked around in the addon until invidious fixes it?

for example addon can redirect https://youtu.be/BiiPDwCbzbM to https://www.youtube.com/watch?v=BiiPDwCbzbM.
or just add the watch?v= for now to the invidious url ?

**Comment by rezad1393** [comment]
https://youtube.com/live/ZPnlpbymGZc 
these videos are also not correctly redirected.

these issues causes a lot of pain for user of invidious and maybe a **temporary** workaround here would help.
for example converting all these link, in the addon process, to the /watch?v= for now.

**Comment by rezad1393** [comment]
what makes this so bad is that user loses the link.
if I open many links and they all go to homepage instead of actual video page, there is no back button for it to go back and find the link I opened.

that's why I asked for a workaround for now.
