### ISSUE TITLE
causing weird errors with websites

### ISSUE THREAD

**Issue by cyberhardt** [libredirect/browser_extension#765]
the extension seems to be interfering with the loading of images and videos. I know it is libredirect because I've tested my extensions one by one. no images/videos seem to be loading. I'm using version 2.7.0 released today.

**Comment by aurtzy** [comment]
Hey @cyberhardt, I was just about to report what I believe is the same bug you're encountering - can you try setting the "Unsupported iframes handling" option for Twitter to "bypass"?

**Comment by candlew1ck** [comment]
Same issue here, and changing the setting mentioned by @aurtzy fixed it. But why twitter? None of the images from the sites I'm visiting are from twitter. That's weird.

**Comment by cyberhardt** [comment]
@aurtzy yep, that seems to be the issue. odd.

**Comment by ManeraKai** [comment]
Show me a page example.

**Comment by cyberhardt** [comment]
@ManeraKai 

![image](https://github.com/libredirect/browser_extension/assets/107224222/91d84f96-e9da-4a7d-95a7-aff083a13500)

**Comment by ManeraKai** [comment]
This is not happening to me, here are my settings:
![image](https://github.com/libredirect/browser_extension/assets/40805353/b5deb2da-a01b-421c-9055-b132e0993095)

**Comment by cyberhardt** [comment]
same settings here, but media doesn't load unless I set it to bypass

**Comment by aurtzy** [comment]
I am able to reproduce this issue with a fresh Firefox profile, adding this extension, enabling Twitter and switching only the "Unsupported iframes handling" setting to "block".

Could some external factor be causing this if @ManeraKai can't reproduce it? I'm currently seeing this on the Firefox Flatpak for Linux, version 115.0.2 if that helps reveal anything.

It seems like images specifically are being blocked by LibRedirect. Videos still work fine. This is what the network tab in the console looks like for this page:

![screenshot_2023-07-22T0321](https://github.com/libredirect/browser_extension/assets/65694715/54c2a970-f3b8-4209-85ec-6782a8dc6488)

**Comment by davidkopp** [comment]
I have the same issue. However, a change of the Twitter settings didn't work for me. Instead, I had to change the YouTube setting "Unsupported iframes handling" to bypass.

**Comment by ManeraKai** [comment]
Try this zip out and see: [libredirect-2.7.1.zip](https://github.com/libredirect/browser_extension/files/12136156/libredirect-2.7.1.zip)

**Comment by davidkopp** [comment]
> Try this zip out and see: [libredirect-2.7.1.zip](https://github.com/libredirect/browser_extension/files/12136156/libredirect-2.7.1.zip)

Works for me :) Thank you!

**Comment by cyberhardt** [comment]
@aurtzy videos do load here, my bad. the thumbnails weren't loading, that was it. btw, I'm on the latest librewolf

**Comment by aurtzy** [comment]
No worries, I just thought it was something worth mentioning in case there was more to the issue.

The zip seems to work fine for me too!
