### ISSUE TITLE
If using localhost instance type, pop-up is missing "Redirect to Original" etc

### ISSUE THREAD

**Issue by Victor239** [libredirect/browser_extension#766]
I've swapped over to using `localhost` instance type for Teddit because those instances are often blocked for the past week or two. 

When I go to the localhost site the pop-up doesn't show the handy links for `Switch Instance`, `Copy Original` or `Redirect to Original`. I'd like if they were all present, and that `Switch Instance` switches to a public instance if pressed.

**Comment by ManeraKai** [comment]
> and that Switch Instance switches to a public instance if pressed

I'll do all except this one.
