### ISSUE TITLE
Add Marginalia's Wikipedia viewer

### ISSUE THREAD

**Issue by walking-octopus** [libredirect/browser_extension#769]
While not strictly a privacy-focused front-end, it is quite amazing for readability and may fulfill the function of a privacy tool as a side-effect. It uses its own local ZIM data-dump, so no data is sent to Wikipedia, but some articles may be missing, so there may need to be a mechanism for fallback.

Home page: https://encyclopedia.marginalia.nu/
Search: https://encyclopedia.marginalia.nu/find/chair
Article: https://encyclopedia.marginalia.nu/article/Chair

**Comment by ManeraKai** [comment]
@soulspark666 There's already an extension for wikiwand.

**Comment by soulspark666** [comment]
Ya, I saw that but why get one more.....
More like it will be a good addition to libredirect.

**Comment by ManeraKai** [comment]
I see the idea but at the end of the day it's a redesign not a privacy frontend. Using [Redirector](https://einaregilsson.com/redirector/) would be a good way to use it.
