### ISSUE TITLE
Timed redirects

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/browser_extension#770]
- Open the Popup
- Set a timer
- Choose function - Redirect or not Redirect or Hit the `start` button.

This would be useful if you wanna use the actual site for some time.

It should be separate for every frontend than for the whole extension.

**Comment by ManeraKai** [comment]
You can just press Redirect To Original for that to happen. Closing the tab will end your "session" or "time" in using the original site.

**Comment by IkelAtomig** [comment]
Why so ?

We are turning off the redirects for that frontend not the site. So, it shouldn't be making sense. It is like disabling the frontend for that particular time.

**Comment by IkelAtomig** [comment]
It is for a reason it is named as 'Timed'. Until the timer/countdown is over. No redirection takes place.

If the user closes the whole browser then that is something different to consider during implementation.

**Comment by ManeraKai** [comment]
**Timer** is a really niche productivity tools. So it's not worth it to be added and will only complex code.

**Comment by IkelAtomig** [comment]
I really can't argue. Maybe I will add it sometime.
