### ISSUE TITLE
Ping results disappear after removing an instance from the list

### ISSUE THREAD

**Issue by ubergeek77** [libredirect/browser_extension#773]
Previously, it was possible to perform a ping test, then go down the list of unreachable/too slow instances and remove them.

Now, as soon as you remove an instance from the list, the ping results next to all of them completely disappears, making it impossible to systematically remove problematic instances without taking a screenshot of something.

**Comment by 8ullyMaguire** [comment]
It also disappears when adding favorite instances.

**Comment by ManeraKai** [comment]
> I think it would be best if it stayed forever (until the users decides to do a new ping).

Well thanks that made me find a really easy solution to this.
