### ISSUE TITLE
[Request] Redirect from Wikwand to Wikipedia alternatives

### ISSUE THREAD

**Issue by TobiasSekan** [libredirect/browser_extension#774]
Hello, 

can you add redirect from [Wikiwand](https://www.wikiwand.com/) to Wikipedia alternative privacy friendly frontends

Thanks

**Comment by xbdmHQ** [comment]
> Hello,
> 
> can you add redirect from [Wikiwand](https://www.wikiwand.com/) to Wikipedia alternative privacy friendly frontends
> 
> Thanks

That's not private lol or open source, Check out: https://github.com/Metastem/wikiless

**Comment by ManeraKai** [comment]
@TobiasSekan if one is using Wikiwand, then he's deliberately using it there's no point in redirecting from it.
