### ISSUE TITLE
Customise shortcuts

### ISSUE THREAD

**Issue by lonix1** [libredirect/browser_extension#775]
Please add a way to specify the shortcuts, or to disable the extension's default shortcuts.

The default shortcuts clash with other extensions' shortcuts, and there's no way to change them.

**Comment by ManeraKai** [comment]
You can do it from your browser settings `about:addons`:
![image](https://github.com/libredirect/browser_extension/assets/40805353/d3dbbe5d-99b3-47bd-b571-c2e338f6a40a)
