### ISSUE TITLE
new frontend zeronet

### ISSUE THREAD

**Issue by cswarm1** [libredirect/browser_extension#778]
normally you would self host ZeroNet and open it at 127.0.0.1:43110 but if you cant host it or on device where you can run it you can use a ZeroNet Meta Proxy https://zero.acelewis.com/ and a working example https://portal.ngnoid.tv/1HELLoE3sFD9569CLCbHEAVqvqV7U2Ri9d/and https://proxy.zeronet.dev/1HELLoE3sFD9569CLCbHEAVqvqV7U2Ri9d . I would find it really helpfully if LibRedirect could support this. thanks in advance.

**Comment by xbdmHQ** [comment]
> normally you would self host ZeroNet and open it at 127.0.0.1:43110 but if you cant host it or on device where you can run it you can use a ZeroNet Meta Proxy https://zero.acelewis.com/ and a working example https://portal.ngnoid.tv/1HELLoE3sFD9569CLCbHEAVqvqV7U2Ri9d/and https://proxy.zeronet.dev/1HELLoE3sFD9569CLCbHEAVqvqV7U2Ri9d . I would find it really helpfully if LibRedirect could support this. thanks in advance.

Not open source

**Comment by cswarm1** [comment]
code is here https://github.com/ZeroNetX and https://github.com/ZeroNetX/

**Comment by ManeraKai** [comment]
ZeroNet is dead and this fork isn't adding much (60 commits from 2021 is nothing). If you want to redirect the proxies, use [Redirector](https://einaregilsson.com/redirector/).

**Comment by xbdmHQ** [comment]
> code is here https://github.com/ZeroNetX and https://zeronet.io/ sorry forgot to link to the code.

Oh, yeah zero net is not maintained for years and wonder what made you suggest this, this is still up on privacytools.io and probably got it from there, You should maybe consider, privacyguides.org to stay up to date with services…
