### ISSUE TITLE
LibreTotal  Privacy-friendly VirusTotal frontend

### ISSUE THREAD

**Issue by cswarm1** [libredirect/browser_extension#779]
LibreTotal
Privacy-friendly VirusTotal frontend
https://github.com/MugoSquero/LibreTotal

**Comment by ManeraKai** [comment]
This, Librespeed, WTFisMyIP, Send, PrivateBin are not benefiting from redirection. The list of frontends is getting very large, I need to filter them out.

**Comment by IkelAtomig** [comment]
Even then isn't this acting like just a proxy ? There is no point since the hash of file or URL is still got by Virustotal.
