### ISSUE TITLE
front-end for Instagram  Proxigram

### ISSUE THREAD

**Issue by cswarm1** [libredirect/browser_extension#785]
A privacy focused and open source alternative front-end for Instagram.
code https://codeberg.org/ThePenguinDev/Proxigram

**Comment by NoPlagiarism** [comment]
Any Instances?

**Comment by xbdmHQ** [comment]
> Any Instances?

I make a docker when i have time.

**Comment by NoPlagiarism** [comment]
Update: one official instance running on repl... yep. https://proxigram.privacyfrontends.repl.co/

**Comment by ManeraKai** [comment]
Can anyone provide a guide for redirection? I don't have an Instagram account.

**Comment by xbdmHQ** [comment]
> Can anyone provide a guide for redirection? I don't have an Instagram account.

What do routes do you need?

**Comment by ManeraKai** [comment]
All the routes that are supported by Proxigram.
