### ISSUE TITLE
An alternative front-end for Yiffer.xyz

### ISSUE THREAD

**Issue by cswarm1** [libredirect/browser_extension#786]
An alternative front-end for Yiffer.xyz
code https://codeberg.org/programmerpony/yiffest
Public instances
    [yiffest.hackermare.gay](https://yiffest.hackermare.gay/)
    [yiffest.glitch.me](https://yiffest.glitch.me/)

**Comment by ManeraKai** [comment]
Same as porninvidious, see: https://libredirect.github.io/faq.html#suggest_frontend
