### ISSUE TITLE
An alternative frontend for LBRY/Odysee: LibreOdysee

### ISSUE THREAD

**Issue by xbdmHQ** [libredirect/browser_extension#789]
https://github.com/WhateverItWorks/LibreOdysee

**Comment by ManeraKai** [comment]
Similar case to https://github.com/libredirect/browser_extension/issues/784#issuecomment-1661918933

**Comment by xbdmHQ** [comment]
> Similar case to [#784 (comment)](https://github.com/libredirect/browser_extension/issues/784#issuecomment-1661918933)

Not a similar case, If your lazy just say that lol. Either you add it or if I find time and someone might work on it either way, It is backed up and re-branded and this is literally the only LBRY/Odysee frontend already search the entire internet for another.
