### ISSUE TITLE
Switch instance doesn't seem to do anything

### ISSUE THREAD

**Issue by 8ullyMaguire** [libredirect/browser_extension#790]
I've changed my favorite instances, removing an instance I was using and then I've clicked on change instance from a channel page on invidious but it didn't change instances.

libredirect: 2.7.1
Firefox: 115.0.3

**Comment by IkelAtomig** [comment]
TO switch an instance, the instance you are in at the time and the instance you want to go. Both must be selected.

**Comment by ManeraKai** [comment]
For instances thst are not in your favorite list, do this: https://libredirect.github.io/docs.html#preferred_instance
