### ISSUE TITLE
Managed by your organization

### ISSUE THREAD

**Issue by vncastanheira** [libredirect/browser_extension#791]
In order to make Brave accept the extension and not think it was installed against my will, I followed the instructions on the Download page and ran the [brave.reg](https://libredirect.github.io/chromium_reg/brave.reg). 

Now if I go to [brave://management/](url), it says my browser is managed by an organization.

Is this a common behavior of chromium browsers after altering the list of allowed extensions?

**Comment by ManeraKai** [comment]
Yes.

**Comment by ManeraKai** [comment]
The MacOS way doesn't require brave.reg. but it won't have auto updates and also you should keep the extension file in a place where you don't erase it.

Btw you should remove the registery enrty that was inserted by brave.reg in order to completely reverse the windows way.

**Comment by ManeraKai** [comment]
You can use for multiple chromium based browsers, the extension does not write to that folder.
