### ISSUE TITLE
Automatically switch instance when chosen instance returns error

### ISSUE THREAD

**Issue by testman42** [libredirect/browser_extension#793]
with Reddit doing some insane API stuff and scraping mitigations or something, the `Error 429 "Too Many Requests"` is a common sight when using LibRedirect.

Would it make sense to implement something in the extension that would detect this and automatically attempt to find a new instance?
Make it try a few times, but eventually stop in case that all enabled instances are rate limited.

**Comment by nonremittal** [comment]
Seconding this. While some frontends break entirely, (e.g. [Nitter at the moment](https://github.com/zedeus/nitter/issues/983)), others vary by instance.

For example one day an Invidious instance works flawlessly, the next I get
> The media could not be loaded, either because the server or network failed or because the format is not supported.
I have to cycle through instances to find what works, and update my favourite instances list every few days.

The same goes for Libreddit with the 
> Error 429 "Too Many Requests"
response.

The FAQ [is pretty clear](https://libredirect.github.io/faq.html#where_the_hell_are_those_instances_coming_from) the list of instances are their maintainer's responsibility, but how are they sorted in the list of instances? Could there be an option to sort by Health or Ping?

Then once you've selected a list of favourite instances, if one fails to work, an option to either:
- automatically switch to the next instance in the list (like hitting Ctrl + Shift + L for you)
- lower that instance down the list of favorites, so working instances naturally get prioritized
- remove that instance entirely

What counts as 'not working' will vary by site and frontend I suppose. 404s should be obvious, at least? ¯\\_(ツ)_/¯

**Comment by 2zzly** [comment]
**### Constantly having to click 3 times to change 'Switch Instance' on reddit many,many times because of 'Too Many Requests' error.**
**This should be Automatic.
Way too much clicking to find a working instance**

**Comment by testman42** [comment]
Alternatively, maybe we should bring this up with Teddit developers, asking them to implement instance switching functionality in Teddit itself.
Invidious already has something like that.
Now that I think about it, this issue is relevant to Invidious as well.
It often happens to me that Invidious instance fails to play video, and refreshing does not help, so I have to switch instance.
But again, same situation as with Teddit. Should switching be done by a browser extension, or should the functionality be built into the platform itself?

**Comment by nonremittal** [comment]
> Should switching be done by a browser extension, or should the functionality be built into the platform itself?

I think it's outside the project's goal as a redirector, since then it would have to parse specific sites/frontends? e.g. my suggestion above, the extension might have to look for "Too Many Requests" on a Reddit alternative one day, something else the next.

Might be worth bringing up with the maintainers of the instances that LibRedirect pulls from? Some sort of "currently working?" entry in the tables would be great. Or if a developer would be willing to create an "over-list" for Invidious, Nitter, Teddit, etc? (User voting? Scripts to check instances, as above? Very patient devs reading all the issue trackers for us? 😅)

**Comment by ManeraKai** [comment]
Use [Frontends Manager](https://github.com/libredirect/frontends_manager) to solve the Too Many Requests problem

**Comment by Sertonix** [comment]
Just redirecting when it fails would not be good enought. That may try the same instance multiple times. Or constantly loop if you are not connected to the internet.
There would need to be a system that checks & stores the health of the instances and then uses that to decide which instance to switch to. The detection could also be simpler by having a "mark as dead" button that excludes the instance for a while.

**Comment by nonremittal** [comment]
Yup the problem (as I understand it) is there's no universal way to signal 'this is a working instance' if that could mean different things to different websites/frontends/users. e.g. Invidious' [instances list](https://api.invidious.io/) just describes 'health' as uptime/downtime percentage. Nitter [has now added](https://github.com/zedeus/nitter/wiki/Instances) a 'working' entry.

I came across [Farside](https://github.com/benbusby/farside) earlier, which is like a web alternative to LibRedirect. It runs a script every 5 mins to compile a list of working instances, but from the README it sounds like that just checks ping and response code. And from a privacy point of view, then you're passing a URL to one website each time.

Overall I agree that #804 is probably the best way to go.

**Comment by ManeraKai** [comment]
Will complete discussion in #804.
