### ISSUE TITLE
Make pinging faster

### ISSUE THREAD

**Issue by Jpxe** [libredirect/browser_extension#797]
Pinging services is really slow. Especially if you get slow ones at the beginning. Could it be made faster, maybe by pinging all or several services at once?

**Comment by nonremittal** [comment]
There's also the issue where if you add an instance while pinging is in progress, it cancels the whole process.

**Comment by ManeraKai** [comment]
Well I made it consequent so no ping will affect the other. And it's pinging 3 times and take an average bc there's no ping function in JavaScript and there are caching problems.
