### ISSUE TITLE
Allow users to sort/rearrange favorite instances

### ISSUE THREAD

**Issue by nonremittal** [libredirect/browser_extension#798]
Since instances are already cycled through in order, it would be great if users could easily rearrange their chosen instances.

This is currently possible, e.g. by deleting your list then re-adding instances in the order you want.

Drag-and-drop might feel out of place, maybe 'move up' and 'move down' arrows? Something like this:
![instances](https://github.com/libredirect/browser_extension/assets/58081816/5932beaf-e6dc-4d6b-b63a-f83841e4994f)

**Comment by ManeraKai** [comment]
Apart from cosmetic reasons the selection is always random.
