### ISSUE TITLE
[Wikipedia][DE] Difference between 'Copy Original' and 'Redirect to Original'

### ISSUE THREAD

**Issue by TobiasSekan** [libredirect/browser_extension#800]
Hello, there is a difference between the links from 'Copy Original' and 'Redirect to Original' on Wikipedia (German)

Input:
https://de.wikipedia.org/w/index.php?title=Spezial:Suche&search=Just-in-sequence-Produktion

Libredirect result:
https://wikiless.esmailelbob.xyz/w/index.php?title=Spezial%3ASuche&search=Just-in-sequence-Produktion&lang=de

'Copy Original' result:
https://wikipedia.org/w/index.php?title=Spezial%3ASuche&search=Just-in-sequence-Produktion

'Redirect to Original' result:
https://de.wikipedia.org/wiki/Just-in-sequence-Produktion
(maybe it is the original input, but I can't catch it)

**Comment by Sertonix** [comment]
The "copy original" redirects to the "Redirect to Original" result*.
* But the language is lost which can cause errors!
So the "lang" parameter of the url should be converted back into the subdomain (eg. "de.wikipedia.org").
