### ISSUE TITLE
"Switch instance" for multiple selected tabs

### ISSUE THREAD

**Issue by testman42** [libredirect/browser_extension#801]
Would it be possible to make extension apply relevant action for all of the selected (Shift+Click) tabs, such as Switch Instance or Redirect to Original from the extension's context menu?
As in, do Firefox and Chromium allow this?

**Comment by ManeraKai** [comment]
It's a nice suggestion, but it's not worth it to add more code for a feature like that.

**Comment by IkelAtomig** [comment]
Really a cool feature might look on it.
