### ISSUE TITLE
Vivaldi blocking v2.7.1?

### ISSUE THREAD

**Issue by Sapiosenses** [libredirect/browser_extension#802]
Been using LibRedirect since early this year.

Was on 2.3.4, installed latest 2.7.1 today.

Besides all sorts of missing features and instances I had been using previously, it wasn't redirecting at all, couldn't figure out how to make it do so.

Vivaldi also seemed to be blocking it when I tried to go to certain settings pages.

When I reverted to 2.3.4, problems went away.

Weird thing is, I thought this extension used the same identity text string for both versions?

![Screen Shot 2023-08-22 at 5 43 53 PM](https://github.com/libredirect/browser_extension/assets/12429261/a0493ab7-6344-44ce-ad88-ad0489242d5b)

**Comment by ManeraKai** [comment]
> Weird thing is, I thought this extension used the same identity text string for both versions?

Yes it does.

Are you on windows?

**Comment by Sapiosenses** [comment]
> > Weird thing is, I thought this extension used the same identity text string for both versions?
> 
> Yes it does.
> 
> Are you on windows?


That particular experience was on macOS but I can test on Windows or Linux as well but no time to do that today.

I want to go back and see exactly why it wasn't redirecting - I guess you removed all the default/bundled instances or something?

But also in what situation that "page blocked" came up. Can't remember exactly and have been too busy to re-test.

**Comment by ManeraKai** [comment]
It is working on linux. We do [want a volunteer](https://fosstodon.org/@libredirect/110761304362599760) to make us have a way of installing LibRedirect properly on MacOS,
