### ISSUE TITLE
Indie Wiki Buddy as option for Fandom etc. 

### ISSUE THREAD

**Issue by MrDowntempo** [libredirect/browser_extension#803]
I appreciate the BreezeWiki alternative to Fandom wikis. There is another extension, Indie Wiki Buddy, which will also use breezewiki instead of Fandom wikis, but before it resorts to that, it has an independently curated list of alternative wikis for specific topics that it will redirect you to first. This, IMHO, is a better solution for wiki redirection, but its a shame that I need a separate extension to accomodate it, when, since their data is public, it should be possible to adapt it to a source in libredirect.

The Indie Wiki Buddy data:
https://github.com/KevinPayravi/indie-wiki-buddy/tree/main/data

**Comment by ManeraKai** [comment]
It better be a separate extension, like Old Reddit and Startpage: https://libredirect.github.io/faq.html#suggest_frontend
