### ISSUE TITLE
User defined instances list from custom URL

### ISSUE THREAD

**Issue by NoPlagiarism** [libredirect/browser_extension#804]

**Comment by nonremittal** [comment]
100% behind this! Maybe a "Custom" option in _General -> Fetch public instances_ which then brings up a URL bar?

Then whether it's a human/crowd-sourced list or a script similar to the libredirect/instances fetcher, that's left to the user 😉 But with how fast frontends break before a new version and public instance is up and running again, I could see folks curating a list of known good instances.

**Comment by Sertonix** [comment]
There would also need to be an option for a refresh interval and maybe a refresh button.

**Comment by heyarne** [comment]
@Sertonix I'd argue a default interval of 24h is probably enough. Having too many options can be a sign of bad design, but maybe hiding it in an "advanced" tab would be worth it for those who disagree.

**Comment by ManeraKai** [comment]
> hiding it in an "advanced" tab would be worth it for those who disagree.

I guess I won't go that path. I won't have time to maintain all those advanced or experimental features. Redirector is an advanced extension, but I won't make LibRedirect advanced.

I'm trying to fix this problem in a simple way with Frontends Manager, but I still need to understand Rust. I hope I will be able to finish it soon.
