### ISSUE TITLE
Vivaldi not auto-redirecting on 2.7.1

### ISSUE THREAD

**Issue by KraXen72** [libredirect/browser_extension#806]
![image](https://github.com/libredirect/browser_extension/assets/21956756/46694a78-3047-4ba2-ac27-199d87cdd00e)
These are my settings. When I enter a link, it does not redirect. I have to manually click the redirect button in the popup (then it works). I would like it to auto-redirect the links.

**Comment by ManeraKai** [comment]
It's similar to how [brave](https://github.com/libredirect/browser_extension/issues/359) was doing before, the problem isn't on LibRedirect's side.

**Comment by KraXen72** [comment]
well the redirector extension works in vivaldi

**Comment by ManeraKai** [comment]
Have you tried backing up and resetting the settings?

**Comment by KraXen72** [comment]
no, i have not. don't really care now lol. i just use redirector. however, if you want to resolve this issue for other vivaldi users, i can try that. (let me know if yes)

**Comment by ManeraKai** [comment]
yes ofc
