### ISSUE TITLE
Click to load frame. Reduce unnecessary bandwidth usage for the instances

### ISSUE THREAD

**Issue by Liokardo** [libredirect/browser_extension#807]
Click to load frame. Reduce unnecessary bandwidth usage for the instances.

Should have it work without Javascript if it's possible. Else, dont put click to load when no Javascript.

**Comment by ManeraKai** [comment]
This is really hard to accomplish, knowing the iframe dimensions and everything, will fail most of the time (after seeing how iframes are complicated like custom twitter and youtube iframes).
If you don't want iframes, you can set the `Redirect Type` => `Only Not Embedded` and if you want more privacy, you can set `Unsupported iframes handling` => `block`.
