### ISSUE TITLE
wiki.metastem.su won't actually load pages through LibRedirect

### ISSUE THREAD

**Issue by QuestioningEspecialy** [libredirect/browser_extension#808]
Steps:

1. go to DuckDuckGo.com
2. search: bird wikipedia
3. click Wikipedia link (https://en.wikipedia.org/wiki/Bird)
4. get redirected to metastem (https://wiki.metastem.su/wiki/Bird#/)
5. see nothing but the main page
6. notice the url appears correct, but I'm just looking at an English search page
7. search: bird
8. click the result (https://wiki.metastem.su/wiki/Bird#/wiki/Bird/en)
9. notice the link's oddness (/wiki/Bird#/wiki/Bird/en)
10. open the site's main page like normal
11. search: bird
12. click the result (https://wiki.metastem.su/#/wiki/Bird/en)
13. notice how much shorter the link is

Seems like LibRedirect is getting the site's link mixed up.

**Comment by xbdmHQ** [comment]
> 

Because it's not wikiless or wikipedia, It his own version.

**Comment by ManeraKai** [comment]
@xbdmHQ is right about this. I'm gonna close the issue.
