### ISSUE TITLE
YouTube channels don't properly redirect to FreeTube

### ISSUE THREAD

**Issue by Flopblopper** [libredirect/browser_extension#809]
Clicking on or entering a direct link to a YouTube channel results in FreeTube stating that the channel does not exist. However, if you manually add the "freetube://" prefix to the link, the channel properly opens in FreeTube.

I'm using the Firefox version of Libredirect

**Comment by ManeraKai** [comment]
Fixed in https://github.com/libredirect/browser_extension/pull/794
