### ISSUE TITLE
Trouble with getting maps working

### ISSUE THREAD

**Issue by MarkG-108** [libredirect/browser_extension#812]
Hello.  I have tried both OpenStreetMap and FacilMap as the set frontend within the settings.  Both of these frontends do work if I explicitly type "maps.google.com" within the URL of the browser I'm using (that being Firefox, 102.14.0esr on Debian Linux).  However, neither of them work when I click on a URL which links to a Google Map location ([example](https://www.thriftstore.ca/locations/), see Salvation Army Thrift Store location page --> all the Google Map location links open a Google Map site, rather than an OpenStreetMap or FacilMap site).  How can I fix this?

**Comment by tobika** [comment]
Same for me, even if I type maps.google.com directly
Version: 2.8.0

**Comment by ManeraKai** [comment]
Re-open this issue if the problem still persists in newer versions. I'll try to improve osm and facil redirection more.
