### ISSUE TITLE
Binternet URL Schemes

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/browser_extension#814]
Support the exact URL schemes of Binternet with help from the developer of Binternet @ahwxorg after changes in the frontend and integrate in extension for better user functionality.

**Comment by Ahwxorg** [comment]
I have added some "maybe's" to the dev branch, but I have not gotten it working yet. I'll probably spend some time on it again soon.

**Comment by ManeraKai** [comment]
Will close this till it gets completed on Binternet's side.

**Comment by ManeraKai** [comment]
Any updated @Ahwxorg?

**Comment by ManeraKai** [comment]
Anyone?

**Comment by Ahwxorg** [comment]
Well honestly I've been more focussed on github.com/Ahwxorg/LibreY. I will try to implement a fix whenever I feel like it. It's not really on my important list since Binternet needs a rewrite anyways...
