### ISSUE TITLE
Add test conditions to repository

### ISSUE THREAD

**Issue by 1fexd** [libredirect/browser_extension#815]
Hi, 

do you guys have something like unit tests where you test if your rewrites to free frontends actually work?

Kind Regards

**Comment by IkelAtomig** [comment]
I don't understand the question actually.

**Comment by 1fexd** [comment]
In https://github.com/libredirect/browser_extension/blob/master/src/assets/javascripts/services.js#L114 you rewrite regular URLs to libre frontends - but are there actually any tests (have you heard of unit testing?) that ensure the functionality is working correctly?

**Comment by IkelAtomig** [comment]
Yeah, I have set of URLs in a markdown file. I just open the link and it extension redirects. I have specific sites to check for embeds.

I am the tester. I rigorously test every frontend whether it is changed or not to ensure it is functional before releasing both in chromium (Need to check on other Chromium browsers too though in later time) and Firefox.

**Comment by 1fexd** [comment]
Would it be possible to include this file in the repo? Or even better, add proper unit tests? Because I am working on an implementation of this extension in Kotlin for my Android app so tests would be super helpful.

**Comment by IkelAtomig** [comment]
Could you please remind me tomorrow ?

**Comment by ManeraKai** [comment]
@IkelAtomig

**Comment by 1fexd** [comment]
Hello, it's tomorrow now :)

**Comment by IkelAtomig** [comment]
[Testing.md](https://github.com/libredirect/browser_extension/files/12582164/Testing.md)

Sorry for the delay. This is mostly I use during testing. Certain things might be missing but major frontends are here.

**Comment by 1fexd** [comment]
I think there should be test cases for this [huge switch](https://github.com/libredirect/browser_extension/blob/c4178fe7b8378692dc5c1c1a6f5cb967842375dc/src/assets/javascripts/services.js#L97). so it can be checked if it actually works.

**Comment by NoPlagiarism** [comment]
Also, I think, Testing.md should be published in repository. So, if someone making any changes

1. They can test it themselves
2. They can add new test for those changes

**Comment by IkelAtomig** [comment]
Yeah, sure. I will add it. Just busy IRL.

**Comment by 1fexd** [comment]
Maybe re-open this until you have time?

**Comment by IkelAtomig** [comment]
Good Idea.

**Comment by ManeraKai** [comment]
Any updates @IkelAtomig?

**Comment by IkelAtomig** [comment]
Will be uploaded during the next release.

**Comment by NoPlagiarism** [comment]
With merging #903, this issue will look very interesting

**Comment by IkelAtomig** [comment]
Ah shit, I really need to get back here. Life sucks ...

**Comment by ManeraKai** [comment]
@IkelAtomig

**Comment by IkelAtomig** [comment]
ETA Sunday. Promise.
