### ISSUE TITLE
Errors in Chromium in v.2.8.0

### ISSUE THREAD

**Issue by 3xploiton3** [libredirect/browser_extension#816]
new fresh install got error

![image](https://github.com/libredirect/browser_extension/assets/19517680/e307f59d-95a2-4f78-ba6f-d647db640de1)
![image](https://github.com/libredirect/browser_extension/assets/19517680/99a9096a-ec4f-4b0b-87e9-60d17516d14a)

**Comment by IkelAtomig** [comment]
It is not a problem. It is meant for Firefox. Firefox reads but chromium does not.

The other errors were found out during internal testing before release. Not a problem too. So, Closing.

**Comment by ManeraKai** [comment]
> The other errors were found out during internal testing before release. Not a problem too. So, Closing.

No I thought the last error got away.
