### ISSUE TITLE
reddit not redirected in any way, although i've working instance😡😡😡

### ISSUE THREAD

**Issue by aicynide** [libredirect/browser_extension#819]

**Comment by ManeraKai** [comment]
Give me an example link, and show me a screenshot of your settings.

**Comment by ManeraKai** [comment]
I'll re-open the issue once you reply.

**Comment by Gooferball69** [comment]
> Wait, I'm walking in crowdy footpath eating shwarma

dude reply

**Comment by Gooferball69** [comment]
@aicynide
