### ISSUE TITLE
TwitchIs frontend for Twitch

### ISSUE THREAD

**Issue by Victor239** [libredirect/browser_extension#822]
Found this: [source](https://github.com/martink635/twitchls) and a [hosted frontend](https://twitchls.com/).

**Comment by xbdmHQ** [comment]
> Found this: [source](https://github.com/martink635/twitchls) and a [hosted frontend](https://twitchls.com/).

Outdated and it't not a privacy frontend that blocks ads, trackers, etc.

**Comment by ManeraKai** [comment]
The [about](https://twitchls.com/about) page explains really well why this project exists, but yeah it's not meant to be a privacy frontend in the first place.
