### ISSUE TITLE
MacOS Safari extension

### ISSUE THREAD

**Issue by lothar-cell** [libredirect/browser_extension#825]
Hey guys, it would be great to have Libredirect in Safari. Yes, there's privacy redirect for which I payed for, but it's very barebones, not in active development and the developer is too smug to handle requests.
So yeah, I love Libredirect in Firefox and would be awesome to have it in Safari, which is my main browser.

**Comment by ManeraKai** [comment]
Safari needs a while code rewrite in another language. We can't do that. I dom't have a mac too.

**Comment by lothar-cell** [comment]
As for the Mac part, there's always virtual machines.

**Comment by ManeraKai** [comment]
And as for learning a whole new language 😅

**Comment by lothar-cell** [comment]
Yeah, I have no answer for that:) Anyway, thanks for taking the time to reply.
