### ISSUE TITLE
I cannot get it to redirect Google Maps to either OpenStreetMap or FacilMap

### ISSUE THREAD

**Issue by MarkG-108** [libredirect/browser_extension#826]
It does not work.  I suspect it may have something to do with Google Maps now appearing with the default URL (google.com/maps/) rather than the previous URL (maps.google.com), but I'm not sure.  I speculate this because the default URL of google seems to be given a pass.  I notice that when I manually enter the URL _maps.google.com_ that my browser does immediately redirect it to OpenStreetMap.  But, as I mentioned, Google Maps now appears with the default URL, and this is not picked up by libredirect.

**Comment by ManeraKai** [comment]
This new default url is already detected by LibRedirect, I tried this url and it redirected to osm: https://www.google.com/maps/@40.9376577,40.3325112,12z?entry=ttu. Btw try with v2.8.1, we just released it.

**Comment by ManeraKai** [comment]
Hello?
