### ISSUE TITLE
popup button is gone

### ISSUE THREAD

**Issue by WorldsEndless** [libredirect/browser_extension#828]
For a few happy weeks my Linux Firefox had the poppup button on my toolbar. I noticed that button never appeared on my Windows wachine, and after a "reset to defaults" lapse in judgement it is now gone from my Linux, too. There used to be a link on the front page of preferences to enable the popup, too, but that is gone as well (and I never saw it there on Windows). This might be a general FireFox issue, but I'm not sure. I'm mostly posting here in case anyone else is dealing with this.

**Comment by ManeraKai** [comment]
Did you right-click on the toolbar and then Customize?

**Comment by ManeraKai** [comment]
I'll re-open the issue if you replied, I assume it's just because you didn't customize the toolbar.
