### ISSUE TITLE
YT Music being redirected with only 'YouTube' enabled

### ISSUE THREAD

**Issue by RyanHx** [libredirect/browser_extension#830]
In the extension settings I have YouTube enabled and YT Music disabled, but when I navigate to https://music.youtube.com/ it tries to redirect the page to FreeTube (my setting for YouTube). 

I see that on [this line](https://github.com/libredirect/browser_extension/blob/3db9e96888f853061b4e2abd752335fc003a721c/src/config.json#L130C45-L130C45) the music.youtube.com domain is a target for the standard `youtube` setting, which seems like a mistake as it's also in the `youtubeMusic` category in that same file. I'm not sure if removing that line would fix this behaviour or if there's more to how the extension picks up redirect targets, that was just the first thing I found on skimming through.

Running on Firefox 118.0.2 (64-bit), Windows 10.

**Comment by ManeraKai** [comment]
This is happening bc of this: https://github.com/libredirect/browser_extension/issues/823

**Comment by RyanHx** [comment]
In that case would it be possible to have the YouTube frontend available in the YT Music specific settings to satisfy that feature request? Since they're seperate categories in the extension it's odd that one setting overrides the other.

**Comment by RyanHx** [comment]
Unfortunately the behaviour remains unchanged with this update; enabling `YouTube` also redirects Youtube Music even with `YT Music` disabled - tested with a fresh install of the extension.

**Comment by ManeraKai** [comment]
I changed the code but I still didn't release?

**Comment by RyanHx** [comment]
Sorry, I saw the version bump in one of the adjacent commits so thought it released. I'm happy to test the changes though.

**Comment by ManeraKai** [comment]
Here you go: [libredirect-2.8.2.zip](https://github.com/libredirect/browser_extension/files/13058287/libredirect-2.8.2.zip)
Follow the instructions here: [Install the zip package on Firefox (temporarily)](https://github.com/libredirect/browser_extension#install-the-zip-package-on-firefox-temporarily)

**Comment by RyanHx** [comment]
2.8.2 seems to still be redirecting YT Music  - https://music.youtube.com/ opens freetube. Here's a copy of my settings for you to try: [libredirect-settings-v2.8.2.json](https://github.com/libredirect/browser_extension/files/13059189/libredirect-settings-v2.8.2.json)

**Comment by ManeraKai** [comment]
I'm stupid sorry: [libredirect-2.8.2.zip](https://github.com/libredirect/browser_extension/files/13060122/libredirect-2.8.2.zip)

**Comment by RyanHx** [comment]
Cheers, can confirm that release fixes it :)

**Comment by RyanHx** [comment]
Hey there, I was wondering if we could get this change pushed to the public addon? We still seem to be on 2.8.1 on Firefox with the same behaviour as this original issue. Manually installing the addon via a file I think only lasts for a single session.

**Comment by ManeraKai** [comment]
We'll try to release.
