### ISSUE TITLE
Valid Youtube Regex Breaking Redirects

### ISSUE THREAD

**Issue by Elteeb96** [libredirect/browser_extension#831]
Currently I am adding exclusions for the youtube homepage and the regex seems to keep failing, simply not allowing for any redirect at all. (Idea was to use the signed in discovery logic in youtube and have the videos I want to play from it via freetube) I have checked all my other extensions for conflicts and I have not seen any. 
Let me know if there is any other information you need that would help.

The regex:
(https:\/\/www\.youtube\.com\/)$

Browser: Firefox (Flatpak 118.0.2)
OS: Linux (Arch)
Extension Version: 2.8.1

Validation of the regex from regex101 below.
![image](https://github.com/libredirect/browser_extension/assets/1544408/68bb7869-0af3-4c17-82db-d0cb20d27eed)

**Comment by IkelAtomig** [comment]
Maybe add /home or /trending at the end ?

**Comment by ManeraKai** [comment]
The code doesn't seem to have any problem: https://github.com/libredirect/browser_extension/blob/ea53506c729b961b815bb56e6db4db4e2c36f5d7/src/assets/javascripts/services.js#L790
Try this regex: `^https?:\/\/(www\.)?youtube.com\/?$`

**Comment by ManeraKai** [comment]
I suggest you open the video in a new tab, it will redirect that way.
