### ISSUE TITLE
Add Freedium (alternative frontend for Medium)

### ISSUE THREAD

**Issue by dinesh-58** [libredirect/browser_extension#832]
[Freedium](https://freedium.cfd/) shows the entire content of paid articles. Out of the existing alternatives, Scribe can't bypass the paywall and LibMedium doesn't even load for me. 

Their github organization is [here](https://github.com/Freedium-cfd). Don't really know how privacy-friendly they are though.

**Comment by ManeraKai** [comment]
It's not a privacy frontend, and I don't want to add paywall bypass frontends to LibRedirect.
