### ISSUE TITLE
Bringing Lingva Translate back

### ISSUE THREAD

**Issue by A-7666** [libredirect/browser_extension#835]
> [2.8.1](https://github.com/libredirect/browser_extension/releases/tag/v2.8.1) [Latest](https://github.com/libredirect/browser_extension/releases/latest)
> What's Changed
> Removed <....> LingvaTranslate

Why so?

Please bring Lingva Translate back

**Comment by ManeraKai** [comment]
Bc it's unmaintained for more than 9 months.

**Comment by IkelAtomig** [comment]
We will not bring Lingva back until there is development or any updates from the main devs such as Project is not dead we are on break.

**Comment by NoPlagiarism** [comment]
- Instance list is not updating
	- Even those instances, that you mentioned. Still waiting to be in official list
		- https://github.com/thedaviddelta/lingva-translate/pull/171
		- https://github.com/thedaviddelta/lingva-translate/pull/172
	- Even official instance stopped working
-   No one updates dependencies => More chances, that Lingva can become vulnerable

**Comment by ManeraKai** [comment]
All the things @NoPlagiarism mentioned are explaining how Lingva is unmaintained. If you want, you can use [Redirector](https://einaregilsson.com/redirector/) for custom redirects.

**Comment by ManeraKai** [comment]
Unmaintained frontends won't be in LibRedirect, for security and support reasons.
