### ISSUE TITLE
[Feature] Redirect Youtube only on video pages

### ISSUE THREAD

**Issue by reuseman** [libredirect/browser_extension#836]
The idea would be to have youtube redirect on an alternative only if the loaded page is a video. This gives the possibility to use their recommended section

**Comment by NoPlagiarism** [comment]
Ok.. 
If you wanna use recommendations I recommend you using [YT-Siphon](https://github.com/d3vr/yt-siphon) instead of LibRedirect. You can open video on YT and do `ALT-J` thing

**Comment by ManeraKai** [comment]
Add this exception to the regex: `^https?:\/\/(www\.)?youtube.com\/?$`
And when opening a video, open it in a new tab.

**Comment by ManeraKai** [comment]
https://github.com/libredirect/browser_extension/issues/845#issuecomment-1785685246
