### ISSUE TITLE
How to make sure the instance list is up-to-date?

### ISSUE THREAD

**Issue by PeterDaveHello** [libredirect/browser_extension#841]
It's not very uncommon to be redirected to a dead instance, I've checked https://raw.githubusercontent.com/libredirect/instances/main/data.json and it seems to be up-to-date, so maybe just the instance list in the extension is not updated? Is there any way to make sure of it, like a manual trigger to update the list? Thanks!

**Comment by ManeraKai** [comment]
> so maybe just the instance list in the extension is not updated?

Before it was merged with the online list, but syncing it with respect to user's choice was a hassle. I started working on [Frontends Manager](https://github.com/libredirect/frontends_manager) as a replacement for instances all together, but I still didn't finish working on it.

**Comment by PeterDaveHello** [comment]
Not sure if I understand correctly, so it's currently only updated with the new version?

**Comment by ManeraKai** [comment]
The local list in your extension is completely separate from the fetched list.

**Comment by PeterDaveHello** [comment]
So right now we don't have a method to update it without update the extension to a new version?

**Comment by ManeraKai** [comment]
Which instance list are you talking about? Are you talking about your custom instance's list? or the one that you is read only?

**Comment by PeterDaveHello** [comment]
Oh, I mean the list in the browser extension :sweat_smile: 

As there's option "Fetch public instances", the instance list seems can be updated, just don't have a button to trigger it?

**Comment by ManeraKai** [comment]
It gets fetched every time you open the settings page, so no need to trigger it :)

**Comment by PeterDaveHello** [comment]
Cool, so I should open the settings page first, let me try it the next time, thanks!
