### ISSUE TITLE
[Feature request][YouTube] Only redirect video pages like /watch /live /shorts

### ISSUE THREAD

**Issue by raniesantos** [libredirect/browser_extension#843]
I want to be able to keep browsing on YouTube itself, but any video page would be redirected to Invidious or Piped etc.

**Comment by NoPlagiarism** [comment]
Duplicate of #836

If you wanna use recommendations I recommend you using [YT-Siphon](https://github.com/d3vr/yt-siphon) instead of LibRedirect. You can open video on YT and do `ALT-J` thing to go to alternative frontend

**Comment by sudoshindo** [comment]
> YT-Siphon

Firefox only

**Comment by J-Lowrance** [comment]
Can this work using the "Excluded from redirecting" feature?
I've tried a few basic things in it, but I can't get anything that only redirects the actual videos.

**Comment by ManeraKai** [comment]
See https://github.com/libredirect/browser_extension/issues/836#issuecomment-1779886031
