### ISSUE TITLE
Only exclude exact url?

### ISSUE THREAD

**Issue by arpuusi** [libredirect/browser_extension#845]
I'd like to be able to exclude only specific url. For me the use case is to be able to browse my youtube feed in firefox, but have all the other links of youtube to be redirected. So, only to exlude the exact "https://www.youtube.com/" but have all the other urls starting https://www.youtube.com/ to be redirected. Also, an option to have "Redirect" in the top-level context menu and preferrably on top, instead of having to navigate to the "LibRedirect" sub-menu for it. I know this might be possible also to tweak as a user on firefox, but I haven't got that far yet.

Thanks!

**Comment by ManeraKai** [comment]
> I'd like to be able to exclude only specific url. For me the use case is to be able to browse my youtube feed in firefox, but have all the other links of youtube to be redirected. So, only to exlude the exact "https://www.youtube.com/" but have all the other urls starting https://www.youtube.com/ to be redirected.

This is already like that.

**Comment by ManeraKai** [comment]
> Also, an option to have "Redirect" in the top-level context menu and preferrably on top, instead of having to navigate to the "LibRedirect" sub-menu for it. I know this might be possible also to tweak as a user on firefox, but I haven't got that far yet.

I can't change that, this submenu is automatic in Firefox.

**Comment by arpuusi** [comment]
> > I'd like to be able to exclude only specific url. For me the use case is to be able to browse my youtube feed in firefox, but have all the other links of youtube to be redirected. So, only to exlude the exact "https://www.youtube.com/" but have all the other urls starting https://www.youtube.com/ to be redirected.
> 
> It's already like that.

Oh, maybe this has been a user error or so. I now see that when accessing the excluded front page and then navigating within there, you can access the video links without redirection, but when opening those links in new tab / middle clicking, makes the redirection kick in. This made me think all the domain was exluded, my bad.

**Comment by arpuusi** [comment]
It's seems it's not possible to use links in video's and channel's descriptions, since that would lead to a new window and redirection, resulting in Freetube interrupting video playback as it thinks it's a link to a channel (this channel does not exist) and the link not opening in browser.

An alternative I found, which differs in function, is Redirector -extension with which you can include eg. youtube.com/watch?=* only or so. When assigned to use freetube: protokol links it opens videos in freetube. It DOES redirect also the left-clicks fron non-directed pages unlike LibRedirect. Just noting. I like how with LibRedirect I can open the videopages withour redirection, but the including-aproach has it's goods too.

My main issue with the whole redirection seems to be on Freetube itself, since there's no way to open the redirects in new window, but it opens them allways in THE SAME window, even if you open a new one for the next redirection. So you can't open multipe windows with redirection in any way, only one.

**Comment by ManeraKai** [comment]
> An alternative I found, which differs in function, is Redirector -extension with which you can include eg. youtube.com/watch?=* only or so. When assigned to use freetube: protokol links it opens videos in freetube. It DOES redirect also the left-clicks fron non-directed pages unlike LibRedirect. Just noting. I like how with LibRedirect I can open the videopages withour redirection, but the including-aproach has it's goods too.

With LibRedirect, when you have an excluded redirection, it makes the whole tab bypassed, so no matter what you do in that tab, it will be bypassed. That's why you need to open in a new tab.

**Comment by ManeraKai** [comment]
> My main issue with the whole redirection seems to be on Freetube itself, since there's no way to open the redirects in new window, but it opens them allways in THE SAME window, even if you open a new one for the next redirection. So you can't open multiple windows with redirection in any way, only one.

Someone else mentioned this too. I myself am annoyed by this too xD. You should open an issue on Freetube's side.
