### ISSUE TITLE
"youtu.be" links not redirected correctly to Invidious

### ISSUE THREAD

**Issue by onchov** [libredirect/browser_extension#846]
ACTION
Click or paste a "youtu.be" video link rather than a "www.youtube.com" video link: https://youtu.be/[video_id]

ACTUAL RESULT
Redirection opens either [invidious_instance_url]/feed/popular (if not logged in) or [invidious_instance_url]/feed/subscriptions (if logged in).

EXPECTED RESULT
Redirection opens [invidious_instance_url]/watch?v=[video_id].

NOTES
Since YouTube started adding a "si" tag for shared videos (possibly a privacy infringing identifier), it should also be removed from redirects.

HOW TO REPRODUCE
1. Click or paste a youtu.be link with a "si" tag, eg https://youtu.be/kszLwBaC4Sw?si=uwDsiFdUiJ8tFCWt
2. A "popular" or "subscriptions" Invidious page is opened (eg https://invidious.protokolla.fi/feed/popular) rather than a matching video redirect (eg https://invidious.protokolla.fi/watch?v=kszLwBaC4Sw).

SYSTEM INFO
I checked that this behaviour affects Firefox and Chrome-based browsers (Brave and ungoogled-chromium) running Windows 10 and Ubuntu-based Linux (Mint).

**Comment by ManeraKai** [comment]
I tried with and without an `si` tag, and it's working perfectly:
https://youtu.be/kszLwBaC4Sw?si=uwDsiFdUiJ8tFCWt => https://invidious.protokolla.fi/watch?v=kszLwBaC4Sw
https://youtu.be/kszLwBaC4Sw => https://invidious.protokolla.fi/watch?v=kszLwBaC4Sw

**Comment by onchov** [comment]
Seems like it's my config then, although suspicious because two different OS's are affected. I'll check another machine(s) tomorrow. Meanwhile, any ideas on how to diagnose it further are welcome.

**Comment by ManeraKai** [comment]
type this in your address bar: about:debugging#/runtime/this-firefox, and then "Inspect" LibRedirect.

**Comment by onchov** [comment]
OK, a little untangling: in FF I previously had PrivacyRedirect installed rather than LibRedirect, and after installing LibRedirect it worked perfectly.
This got me an idea and I removed and reinstalled LibRedirect in Brave, and lo and behold, it's now working with the youtu.be links! FWIW, the version I probably had before was 2.8.0 rather than 2.8.1, not sure if that could be the issue.
Anyhoo, thanks for help, closing and sorry for the noise.
