### ISSUE TITLE
[Feature Request] Allow customizable timeout for pinging instances

### ISSUE THREAD

**Issue by CDeLeon94** [libredirect/browser_extension#848]
When settings up the instances, pining can take a long time. Well, 5 seconds per dead instance. 
Personally, many instances are available within 500ms, and several sub 50ms... I'd like to set a lower timeout so that I can much more quickly test instances and get my redirects working.

**Comment by ManeraKai** [comment]
I can add this slider, but I don't want to make LibRedirect be an advanced extension.
