### ISSUE TITLE
Safari and iOS

### ISSUE THREAD

**Issue by hmlendea** [libredirect/browser_extension#851]
Any plans to make a Safari/iOS version?

The 'Privacy Redirect' extension is so outdated and feature-poor compared to this one.

I feel this is really important since it's usually the phones that are more problematic when protecting your privacy.

**Comment by ManeraKai** [comment]
No plans at all. I don't have any apple product.

**Comment by ManeraKai** [comment]
> I feel this is really important since it's usually the phones that are more problematic when protecting your privacy.

See this [Mobile Support?](https://libredirect.github.io/faq.html#mobile_support)
