### ISSUE TITLE
Freetube Cardova (youtube front end) Support

### ISSUE THREAD

**Issue by Kamalaja** [libredirect/browser_extension#854]
👋 - Hey! I use freetube cardova https://github.com/MarmadileManteater/FreeTubeCordova

as I like the freetube UX and features and I want it as a web app. It would be awesome if libredirect could support it!

Thanks :D

**Comment by ManeraKai** [comment]
I can't make it a web app myself. Someone should make it so, then we'll add it.

**Comment by ManeraKai** [comment]
Having the PWA as not a standalone domain will create a problem:
❌ https://marmadilemanteater.github.io/freetube/#
✔️ https://pwa.freetube.io/

**Comment by ManeraKai** [comment]
Tell me to re-open the issue when there is a PWA that can be accessed from the root path.
