### ISSUE TITLE
[Feature Request] Sync settings with github/gitea repo/gist

### ISSUE THREAD

**Issue by anyone00** [libredirect/browser_extension#855]
Does anyone have a way to sync their settings through a remote config?
Something like a github gist or from gitea?

Updating my settings gets tiring when having multiple devices and browsers.
Now I have to download the config every time and import it to sync.

There is already sync with firefox/brave sync, but I want something
I have more control on as mentioned github gist or somewhere on more private
like gitea instance and for browsers that don't support sync.

My inspiration was that I have a ublock filter list and I have it somewhere
up in the internet. As I update it all my devices will get it.

It is definitely an advanced option, people usually don't have a lot devices like me :) and want to take the extra burden of settings it up probably

Would like to hear from anyone that has setup something similar?

**Comment by ManeraKai** [comment]
> Would like to hear from anyone that has setup something similar?

😈
