### ISSUE TITLE
[Feature request]: Re-add auto-redirect back

### ISSUE THREAD

**Issue by ccuser44** [libredirect/browser_extension#856]
The auto-redirect should be added back to Libredirect.

The feature is very useful because many instances usually do not work. I don't see why it shouldn't be added back.

**Comment by ManeraKai** [comment]
Basically LibRedirect can't know exactly if the instance is running, partially running, or having a server an error. It also is different from e.g Invidious to Piped. Invidious gives 500 Server Error code when if it only didn't find the video. It should give a 404 Not found code. Things got complicated, so we removed it. You can press Switch Instance from the popup, or Shift+Alt+L.

**Comment by ccuser44** [comment]
> Basically LibRedirect can't know exactly or in a complicated way if the instance is running, partially running, having a server error, instance is offline, or you're offline.

> Things got complicated, so we removed it.

Can't you just have said complicated handler then? Also I'm pretty sure it's not that hard to do, just have a JSON file with error coresponding on if the instance doesn't work.

> You can press Switch Instance from the popup, or Shift+Alt+L.

A lot of instances on yt, reddit and twitter are bugged so you have to do this multiple times

**Comment by ManeraKai** [comment]
I tried to improve this instances problem with [Frontends Manager](https://github.com/libredirect/frontends_manager/blob/main/whitepaper.md), but I still didn't finish it completely.
