### ISSUE TITLE
Feature request: FastForward

### ISSUE THREAD

**Issue by aaronliu0130** [libredirect/browser_extension#859]
Is there a filter list for FastForward available? If not, is it planned?

**Comment by ManeraKai** [comment]
No, LibRedirect is only meant to redirect popular websites to privacy friendly frontends.

**Comment by aaronliu0130** [comment]
I don't get why that excludes a filter list for FastForward.

**Comment by ManeraKai** [comment]
Is this filter redirecting to a privacy friendly frontend?

**Comment by aaronliu0130** [comment]
I did some digging: FastForward could specify custom filters during the Manifest v2 days. However Google disallowed executing unpacked/unsigned code in their Manifest v3. This disabled all custom filter lists, and is yet another reason ublock origin isn't moving to v3.

What I meant was creating LibRedirect filters for FastForward, not importing rules from FastForward. But it seems like the days have gone.

**Comment by aaronliu0130** [comment]
Maybe, though that's still possible since the dynamic rules' limit should be enough to cover all instances.

**Comment by ManeraKai** [comment]
You mean the recent modification to Mv3?

**Comment by aaronliu0130** [comment]
IDK how recent it is, but it's gotten to the point where uBO Lite (a Mv3 version of Mv2) can block nearly all of the ads uBO does.
