### ISSUE TITLE
[Feature request] Implement some way for the browser to remember the real backend for the page

### ISSUE THREAD

**Issue by Gooberpatrol66** [libredirect/browser_extension#861]
I'm reluctant to use this extension because most libre frontend instances are more ephemeral than the big websites they're fronting (a few of them were down when I tried out the extension). And usually the instance domain names are not descriptive of what the instance hosts. I'm concerned about leaving a tab open for too long or bookmarking something, and the instance going down, and losing access to that page, and being unable to figure out the backend site it came from.

Could the extension remember if a link is a github/youtube/etc page, and then redirect to new frontends as needed?

**Comment by ManeraKai** [comment]
Just press `Redirect to Original`

**Comment by ManeraKai** [comment]
Can you record me a video?

**Comment by ManeraKai** [comment]
I should make it automatically ask for the bookmark permission, but you can manually enable it from the settings:
![image](https://github.com/libredirect/browser_extension/assets/40805353/a38b67e6-86f8-4ebb-b6b8-c9745b8f67b8)
![Screenshot_20231208_175944](https://github.com/libredirect/browser_extension/assets/40805353/a7c3373a-fe7e-434a-ac61-04aa7617fd56)
