### ISSUE TITLE
Invidious embeds redirecting YouTube links play automatically without user input

### ISSUE THREAD

**Issue by alliedsincro** [libredirect/browser_extension#863]
Have set YouTube redirect to also redirect the embedded links in other websites to Invidious. But in some sites, it just plays as soon as the site loads with no user input. In sites where multiple invidious embeds exist, they even play all at the same time resulting in chaos where all the streams have to be manually reloaded.

The same doesn't happen with other frontends like Piped. They only load when actively clicked upon which is the intended behavior.

Maybe it has something to do with the player the invidious uses which is completely without javascript. In any case, this needs to be fixed

**Comment by ManeraKai** [comment]
Isn't there an option to disable Autoplay in an invidious' settings?

**Comment by MintMain21** [comment]
Yeah, this is something specific to different instances, not the extension itself.

**Comment by ManeraKai** [comment]
Then this problem is on invifious' side, or can be fixed by changing your settings.
