### ISSUE TITLE
looping thorugh selected frontends

### ISSUE THREAD

**Issue by je-vv** [libredirect/browser_extension#864]
Hi !

With youtube and reddit rate limiting frontends, is it possible for LibRedirect to loop through several frontends, not spending more than 10s on each one tried?  In the case of reddit, when all selected frontends fail, perhaps falling back to old.reddit.com might be a less dangerous than plain www.reddit.com...

Thanks !

**Comment by ManeraKai** [comment]
We had this option before, but it's so inconsistent to have. I'm working on [Frontends Manager](https://github.com/libredirect/frontends_manager) to solve the rate limiting problem in instances.
