### ISSUE TITLE
Cycle through instances if link repeatedly opened

### ISSUE THREAD

**Issue by opusforlife2** [libredirect/browser_extension#865]
If some instances aren't working for whatever reason, then the random selection process can tend to repeatedly throw up the bad instances.

If a link is repeatedly opened within a short duration of say, 30 seconds, then the instance list could be cycled through, because such behaviour would only be likely when the user wants to find a working instance.

After the time limit is over, the extension can go back to random instance selection.

**Comment by ManeraKai** [comment]
Knowing if an instance is giving an error or not is not a simple concept: https://github.com/libredirect/browser_extension/issues/856#issuecomment-1817876751
This is he main reason why we removed Auto Redirect.

**Comment by ManeraKai** [comment]
I thought you meant to temporarily remove that instance for 10 seconds if it appeared to not be working.

**Comment by ManeraKai** [comment]
I think this PR will fixed the problem in a better way: https://github.com/libredirect/browser_extension/pull/857
