### ISSUE TITLE
Redirections on front ends

### ISSUE THREAD

**Issue by anxiouslelimo** [libredirect/browser_extension#866]
I opened a medium article which opened in scribe instance but it had an embedded youtube link which is not redirected. 

eg: https://medium.com/@jamesbridle/something-is-wrong-on-the-internet-c39c471271d2
      https://medium.com/@hankgreen/a-decade-later-youtube-remains-a-mystery-especially-to-itself-80a1c38feeaf

**Comment by ManeraKai** [comment]
There's something wrong with scribe instances themselves. They are not allowing embeds to be redirected. See this: https://github.com/libredirect/browser_extension/issues/689#issuecomment-1549020001
This should be fixed on scribe's side.

**Comment by ManeraKai** [comment]
Which instance?
