### ISSUE TITLE
Add Priviblur (Alternative frontend to Tumblr)

### ISSUE THREAD

**Issue by syeopite** [libredirect/browser_extension#867]
Hello! I've recently created an alternative frontend to Tumblr called Priviblur:

https://github.com/syeopite/priviblur

Any chance it could get added to Libredirect?

**Comment by ManeraKai** [comment]
Can you provide examples of how to redirect it?

**Comment by syeopite** [comment]
There's also a special case for when a Tumblr blog uses a custom domain such as https://www.davidslog.com/ but I'm not entirely sure how to reliably detect that since Tumblr blogs can also support custom themes.

**Comment by ManeraKai** [comment]
I'll for now add the main tumblr.com domain.

**Comment by syeopite** [comment]
Awesome thank you so much! :smile:
