### ISSUE TITLE
[REQUEST] More frontends

### ISSUE THREAD

**Issue by darlopvil** [libredirect/browser_extension#871]
Librarian for Odysee:
https://librarian.pussthecat.org/
https://lbry.vern.cc/

LibreY as a meta search engine:
https://librey.baczek.me/instances.php

Lingva as a translator service:
https://github.com/thedaviddelta/lingva-translate#instances

Many other instances from already frontends don't appear in the extension config page. 4get as an example. Here you can have a daily list of all them updated:

https://farside.link/

As always, thank you for your hard work 🤝

P.S.: https://libretranslate.com/ as an instance for LibreTranslate (it isn't in the list)

**Comment by NoPlagiarism** [comment]
Lingva was removed from LibRedirect for being unmaintained. Discussion in #835

**Comment by NoPlagiarism** [comment]
Actually, same for Librarian

PR: https://github.com/libredirect/browser_extension/pull/696

**Comment by NoPlagiarism** [comment]
So.. For [LibreY](https://github.com/Ahwxorg/librey). Actually it's fork of [LibreX](https://github.com/hnhx/librex)

LibreY instances are listed in json file with `"librey": true`

- [JSON File](https://github.com/Ahwxorg/LibreY/blob/main/instances.json): `https://raw.githubusercontent.com/Ahwxorg/LibreY/main/instances.json`

**Comment by darlopvil** [comment]
Being unmaintained means redirection doesn't work? If not, I don't know why isn't implemented, just as long as it works for its purpose (redirection).

For Libre X: Well, I thought that by selecting 'LibreX' among the various search engines, only instances of LibreX would appear. However, I've noticed that it's not the case; it's a mix of instances of LibreX and LibreY. I find it a bit chaotic and disorganized. Wouldn't it be better to separate them as if they were different browsers?

**Comment by ManeraKai** [comment]
> Being unmaintained means redirection doesn't work? If not, I don't know why isn't implemented, just as long as it works for its purpose (redirection).

We won't add unmaintained frontends for security and usability reasons. If you want to use a custom frontend that has been removed or not yet supported, then use [Redirector](https://einaregilsson.com/redirector/).

**Comment by NoPlagiarism** [comment]
> I don't know why isn't implemented

As I said, discussion about Lingva in #835. Please read reasoning there

https://github.com/libredirect/browser_extension/issues/835#issuecomment-1774114547

**Comment by darlopvil** [comment]
My apologies, didn't know the policy behind whether to implement a frontend. I'll take Redirector then and give it a try. 

Thanks for the support and quick responses @ManeraKai @NoPlagiarism

**Comment by ManeraKai** [comment]
> I have a thought, could we list out the rules somewhere for users to reference for [Redirector](https://einaregilsson.com/redirector/) for frontends that Libredirect no longer supports.

@toyboatcash Please open a separate issue about this.
