### ISSUE TITLE
[Android] Mobile-friendly settings layout

### ISSUE THREAD

**Issue by opusforlife2** [libredirect/browser_extension#874]
Right now you need to zoom in to various parts to use them.

Settings tabs are all bunched up at the top of the mobile UI. Unlike on desktop, where there is a proper fixed layout.

It's functional, but usability can be improved. Maybe scrollable tabs?

**Comment by nonremittal** [comment]
Only a decade or so behind there, Mozilla! 😄
Glad this has been implemented but I agree a vertical/phone layout would be super useful. Lots of scrolling around when the complete list of sites is scrunched together.

As a workaround maybe even a setting under general to check/uncheck the sites displayed? I don't know what Bilibili or Pixiv are, but I would like frontends to Fandom and Reddit!
