### ISSUE TITLE
Pinterest -> Redirects don't work

### ISSUE THREAD

**Issue by Nitrousoxide** [libredirect/browser_extension#876]
Take this entry:
https://www.pinterest.com/pin/313211349098097774/

Attempting to use the extension to redirect gets you to here:
https://binternet.ahwx.org/pin/313211349098097774/

Which gives a 404.  The site is working however and can find other images just fine if you search using the front page:
https://binternet.ahwx.org/

You can find the image I believe is in the pintrest pin as the first result here:
https://binternet.ahwx.org/search.php?q=The+Tale+of+the+Two+Brothers

aka:
https://binternet.ahwx.org/image_proxy.php?url=https://i.pinimg.com/originals/38/a4/d9/38a4d9afe64882f1687b85510585d5d1.png

This seems to be generalized problem and not just one with this particular pin.  I believe there needs to be a different translation done of the origonal url to the redirect, though I don't see an obvious method to generate the actual url there from the source, unless I'm finding the wrong picture I guess.

**Comment by ManeraKai** [comment]
How can I get the id `38a4d9afe64882f1687b85510585d5d1.png` from the id `313211349098097774`? This should be on Binternet's side.

**Comment by Nitrousoxide** [comment]
I absolutely agree.  I don't see how you fix this.  But if it's not fixable maybe the redirect should be removed since it won't be able to redirect you to the corresponding page.

**Comment by ManeraKai** [comment]
Let me know if it got changed on Binternet's side.

**Comment by Nitrousoxide** [comment]
there's a pending issue on their github about this with little to no movement on it.  I think this redirect should probably just be removed since it won't work like the user expects.

https://github.com/Ahwxorg/Binternet/issues/13

**Comment by ManeraKai** [comment]
oh we even have an issue ourselves! https://github.com/libredirect/browser_extension/issues/814
