### ISSUE TITLE
YouTube redirection does not work

### ISSUE THREAD

**Issue by pH142857** [libredirect/browser_extension#877]
Firefox, brand new 2.8.1 re-install after some messy bugs, I switched on YouTube redirection, it worked a few times and quickly stopped working on its own.

YouTube redirection is activated:
![libredirect1](https://github.com/libredirect/browser_extension/assets/11050141/f003e3db-1b1d-4901-ba74-1f7c9cb33f65)

But when I load www.youtube.com, I reach YouTube instead of an invidious instance.

My instances ping fine:
![libredirect instances](https://github.com/libredirect/browser_extension/assets/11050141/6b19543c-ab5a-4a82-8c1e-05d3b364b01f)

While on YouTube, If I click the 🔁 instance switching button, I get: `Firefox cannot find the file at moz-extension://6cbb528a-3b11-4e46-a297-1999092c741c/pages/popup/undefined/.`.

**Comment by ManeraKai** [comment]
How did you install the extension?

**Comment by pH142857** [comment]
The normal way, from Firefox Addons page.

**Comment by pH142857** [comment]
Now it works again, but it had switched to interface Poketube on its own (???). I selected Invidious again.

However now, the 🔁 instance switching button reloads the same invidious instance (which is a progress but still not the expected behavior).

**Comment by ManeraKai** [comment]
Your settings file seems to be messed up. You reset your settings right?

**Comment by pH142857** [comment]
So, the invidious instance that kept being reloaded by the switching button was inv.vern.cc/ and I noticed it was in the "add your fav instances" section of the settings (I didn't add it), so I ✖️ deleted it. The immediate effect was that I'm back to the original problem I described in the OP.

To answer your question, I am not aware of a settings file, I only use the settings interface. Docs and FAQ on https://libredirect.github.io are silent about a settings file.

**Comment by ManeraKai** [comment]
No I mean this:
![image](https://github.com/libredirect/browser_extension/assets/40805353/48244591-0d67-42c0-a6b8-89d32d91e2b4)

**Comment by pH142857** [comment]
I hit this button and get the exact same behavior: https://inv.vern.cc/ is back as "favorite instance", Youtube is redirected to https://inv.vern.cc/ and the switch instance button does not switch to another instance. Then I delete https://inv.vern.cc/ from the favorite instance, and Youtube is not redirected anymore.

**Comment by ManeraKai** [comment]
You should add some favorite instances in order to be redirected to them.

**Comment by pH142857** [comment]
Is it really how this is supposed to work? That would make the term "favorite" misleading. 

Anyway on another browser (same Libredirect version 2.8.1), this is not how it behaves, but it seems kinda broken too:
- youtube is redirected to a random instance
- in the Libredirect pop-up, the YT switch instance button works
- but I have no favorite instances declared, and the interface is not like before, it has many occurrences of the "add your favorite instances" section, all empty and `Loading...` forever:
![image](https://github.com/libredirect/browser_extension/assets/11050141/1a83ba4b-5fe8-4a99-939e-20ee2e13b45f)
- and last but not least, the Youtube redirection looks deactivated but is actually active, and there is no dropdown list for the "redirection type" parameter:
![image](https://github.com/libredirect/browser_extension/assets/11050141/8e4900c9-f86a-44f4-a1f6-5f39f7269f25)

**Comment by ManeraKai** [comment]
> but I have no favorite instances declared, and the interface is not like before, it has many occurrences of the "add your favorite instances" section, all empty and Loading... forever:

I did not understand.

**Comment by ManeraKai** [comment]
> and last but not least, the Youtube redirection looks deactivated but is actually active, and there is no dropdown list for the "redirection type" parameter:

The Instance Type should not be appearing for invidious in the first place.

**Comment by pH142857** [comment]
> > but I have no favorite instances declared, and the interface is not like before, it has many occurrences of the "add your favorite instances" section, all empty and Loading... forever:
> 
> I did not understand.

Not sure what you did not understand, but:
- on one browser, the instances section looks like the 2nd pic in the OP (a list of instances that you can ping), 
- on the second browser, it looks like the first pic of my previous msg (several occurences of a "add your favorite instances" with a list that fails to load)



> > and last but not least, the Youtube redirection looks deactivated but is actually active, and there is no dropdown list for the "redirection type" parameter:
> 
> The Instance Type should not be appearing for invidious in the first place.

I am not talking about the instance type but the redirection type, that would normally feature "only embedded", "only not embedded" and "both".

**Comment by pH142857** [comment]
I switched Firefox language to English (US), switched Libredirect off and on again, but nothing changed.

**Comment by OrginalS** [comment]
I have the same problem, Youtube doesn't work, Youtube Music and everything else does. I have the same issue with [Redirector](https://github.com/einaregilsson/Redirector).
Brave browser v 1.62.156 Chromium 121.0.6167.139 Official Build deb package.

Works fine on LibreWolf.

**Comment by ManeraKai** [comment]
If you're having the same issue with Redirector, and clearing cache fixed it. Then it's not related to LibRedirect.
