### ISSUE TITLE
Installing on Chromium/Linux: "Could not load manifest"

### ISSUE THREAD

**Issue by hadi-naqvi** [libredirect/browser_extension#878]
**Error:**
![image](https://github.com/libredirect/browser_extension/assets/92334527/cadbcaa2-3681-4b4e-9e8c-e3350f302529)
**manifest.json:**
![image](https://github.com/libredirect/browser_extension/assets/92334527/7d888689-87ac-4380-b344-d60f87b4335c)
Due to the fact that index.html does not exist in the directory specified by ``manifest.json``, it seems to be causing the "Could not load manifest" error.

Additional Info:
I'm using Brave browser on Linux and attempting to install the extension by:
1. Going to brave://extensions/
2. Enabling Developer Mode
3. Load unpacked --> src folder from repository

**Comment by hadi-naqvi** [comment]
Fixed this issue by installing the packed extension (dragging and dropping the ``.crx`` file onto the brave://extensions/ page) which can be found here:
https://github.com/libredirect/browser_extension/releases/

Note: This is how you're supposed to install the extension on a Chromium-based browser using Linux.

**Comment by ManeraKai** [comment]
> Note: This is how you're supposed to install the extension on a Chromium-based browser using Linux.

It's documented as such that in our [download](https://libredirect.github.io/download_chromium.html) page
