### ISSUE TITLE
Libreddit fork: Redlib

### ISSUE THREAD

**Issue by opusforlife2** [libredirect/browser_extension#879]
Hi. https://github.com/redlib-org/redlib is a maintained fork of Libreddit that has its own instance list at https://github.com/redlib-org/redlib-instances.

Since Libreddit still works most of the time, I think both instance lists can continue to function simultaneously. Though it would be good to mark Redlib instances as separate from Libreddit ones.

**Comment by Victor239** [comment]
Libreddit instances now produce the error `Failed to parse page JSON data: expected value at line 1 column 1` , so it's time to move to Redlib it looks like.
