### ISSUE TITLE
SearXNG sometimes redirects to main page without query

### ISSUE THREAD

**Issue by mooreye** [libredirect/browser_extension#880]
I have Libredirect's searxng set as my default engine in Firefox.

Often when I type something in URL, I get redirected to main page of some SearXNG instance without actually searching the query. This is what happened to me just now after typing a query:

![2024-01-06T16:36:55,724056938+01:00](https://github.com/libredirect/browser_extension/assets/93423596/1c698778-faa3-4d48-812f-60d9a2ba4502)

By pressing `Ctrl+Z` multiple times in the search bar, I was able to go back to the query I typed initially:

`https://search.libredirect.invalid/?q=why+is+the+sky+blue`

**Comment by ManeraKai** [comment]
Is this happening with other instances?

**Comment by mooreye** [comment]
> Is this happening with other instances?

Yes, it seems to happen randomly. I definitely also experienced this with `https://search.bus-hit.me/` and `https://searx.work/` but there were many more.

**Comment by ManeraKai** [comment]
I'm not finding anything in code that would cause this. I need more information.

**Comment by mooreye** [comment]
I actually use Librewolf as my browser, it has additional hardening and maybe that is causing some issues

**Comment by ManeraKai** [comment]
The redirection code in searxng is really simple. There are no problems or even if conditions in it:
![image](https://github.com/libredirect/browser_extension/assets/40805353/b3d7b169-09ea-421f-b2e6-6a0d820109e0)
This is a bug in SearXNG, not in LibRedirect.

**Comment by itscool900** [comment]
The issue is most likely with old SearXNG pages and redirects. Maybe it would help to show what instance LibRedirect chooses, or to have an easy way to remove the last chosen instance. That way, even when redirected from that instance, it is still possible to troubleshoot.
