### ISSUE TITLE
The "Import Settings" & "Export Settings" icons are the wrong way around

### ISSUE THREAD

**Issue by OpenSourceHelperGuy** [libredirect/browser_extension#882]
It is a minor problem in the "General" tab.

I was going to create a pull request to fix this. However, I found that src/pages/options/index.html was included in the .gitignore file and so it does not show up in the source code.

**Comment by ManeraKai** [comment]
Change the .pug files. They are the template files for HTML.

**Comment by ManeraKai** [comment]
Will you make a PR or should I fix it?

**Comment by OpenSourceHelperGuy** [comment]
I've been a bit busy I'll look at it today.
