### ISSUE TITLE
Add Tubo  https://media.ccc.de

### ISSUE THREAD

**Issue by toyboatcash** [libredirect/browser_extension#884]
Code https://github.com/migalmoreno/tubo
instance https://tubo.migalmoreno.com/

Videos 
https://media.ccc.de/v/37c3-11784-lass_mal_das_innere_eines_neuronalen_netzes_ansehen redirects to
http://localhost:3000/stream?url=https%3A%2F%2Fmedia.ccc.de%2Fpublic%2Fevents%2Fdf5ca65a-e3d6-42ae-9805-9bc02821ada4

User Page 
http://localhost:3000/channel?url=https%3A%2F%2Fmedia.ccc.de%2Fc%2F37c3
https://media.ccc.de/c/37c3

Search
http://localhost:3000/search?q=Janna+Schlender&serviceId=2
https://media.ccc.de/search?p=Janna+Schlender

Conferences, not sure if I have the URL correct 
https://media.ccc.de/a
http://localhost:3000/kiosk?serviceId=2&kioskId=conferences
http://localhost:3000/channel?url=https%3A%2F%2Fapi.media.ccc.de%2Fpublic%2Fconferences%2Fforumoe
https://media.ccc.de/c/forumoe19

**Comment by IkelAtomig** [comment]
Already added by #783. What are you trying to establish ?

**Comment by ManeraKai** [comment]
Why is there a need to have a frontend for media.ccc.de? It's not privacy invasive or anything.

**Comment by ManeraKai** [comment]
> Also, I asked if there was a way to change the peer tube instance. https://github.com/migalmoreno/tubo/issues/22 I know this might be more difficult to add but would be really cool future if it gets supported.

Redirecting PeerTube is hard since you need to know ALL peertube instances, which is in thousands. I know this because there was a frontend for PeerTube called SimpleerTube.

**Comment by ManeraKai** [comment]
Bandcamp is not working on Tubo at the moment.

**Comment by aidan-gibson** [comment]
The source is no longer on github but is available here https://git.migalmoreno.com/tubo/

**Comment by IkelAtomig** [comment]
Kai, did you change the source in Instances script ?

**Comment by ManeraKai** [comment]
Yes
