### ISSUE TITLE
Nitter is Dead. Should it be removed from the extension? 

### ISSUE THREAD

**Issue by MintMain21** [libredirect/browser_extension#898]
Looking at the history of Instagram redirections, it seems when Bibliogram shut down that the extension pivoted to using a different frontend. I don't believe any alternate Twitter frontends exists besides Nitter, and it doesn't sound like any should be popping up anytime soon.

Should Twitter redirects be retired then? Or at least disabled by default until further notice?

**Comment by ManeraKai** [comment]
It should be removed and added to https://www.youtube.com/@Bilmok.

**Comment by ManeraKai** [comment]
It should be removed and added to https://github.com/libredirect/browser_extension/issues/892.

**Comment by polak14** [comment]
Nitter is still perfectly usable on local or private instances and a couple of public instances like https://nitter.poast.org

**Comment by ManeraKai** [comment]
You can submit Redirector Rules. And I'll add them to the website https://github.com/libredirect/browser_extension/issues/892

**Comment by anewuser** [comment]
This instance from the [official list](https://github.com/zedeus/nitter/wiki/Instances#public) still working:  https://nitter.poast.org/search?f=tweets&e-nativeretweets=on&q=libredirect

You could've waited for it to go down too.

**Comment by Cynosphere** [comment]
Removing "dead" projects and forcing people to use a second extension feels against the spirit and goals of the project. Please reconsider and do better.

**Comment by seefood** [comment]
One instance of nitter is down, there are many others, there is even a redirector that automagically redirects to a host that is less loaded and not out of API tokens. just cutting away the entire redirection option for twitter without letting the user choose the redirection target on their local browser is kinda harsh.

**Comment by 6Fv** [comment]
Why would you remove this???
Nitter is not "dead".

If you're not able to use Nitter, simply uncheck Twitter. Is that so hard?
Don't disable it for everyone that still uses it...

If you're worried about a negative reflection on this browser extension's reputation, just add a little disclaimer:
> *Hey, in order to get this to work, you'll have to put in a tiny amount of effort*

**Comment by obfuscated-loop** [comment]
Please add back Nitter, it was working fine for me on multiple instances and I do agree upon the fact that it's the users decision to supply working instances within the redirector; I could always make a PR of some updated working instances pre-configured but stuff like this becomes cumbersome updating with the newest alive instances...

 @Seby458 Do you think you could make a PR of your fork to speed up process? Unless a maintainer can revert :+1:
