### ISSUE TITLE
UI / UX Improvement Suggestion

### ISSUE THREAD

**Issue by compilenix** [libredirect/browser_extension#899]
Hey there,
I want to suggest to re-order the popup menu items, to put the most frequently used items closest to the current mouse & keyboard position for ease of use and increased accessibility.

This is how it looks currently:
![Screenshot from 2024-03-09 19-39-35](https://github.com/libredirect/browser_extension/assets/6356150/29233441-de1b-4e06-aabb-ae657be776f7)

And here is my suggestion:
![Screenshot from 2024-03-09 19-39-35-new](https://github.com/libredirect/browser_extension/assets/6356150/7cbad24a-d4cd-4839-9e28-7b362cf2a34a)

What's your thoughts on this?

I'm offering to have a look into the code of the project and creating a PR, if the suggestion is getting accepted.

**Comment by ManeraKai** [comment]
Maybe put only "Settings" at bottom?

**Comment by compilenix** [comment]
So you are thinking something more like this?

![Screenshot from 2024-03-09 19-39-35-new-2](https://github.com/libredirect/browser_extension/assets/6356150/e32c4974-8d07-4148-b16d-539d2577fb94)

I like this variation also.

**Comment by ManeraKai** [comment]
Nice.
