### ISSUE TITLE
TypeError in Chrome on v2.8.2

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/browser_extension#901]
```
Uncaught TypeError: Error in invocation of permissions.contains(permissions.Permissions permissions, function callback): No matching signature.
    at general.js:152:58
````

https://github.com/libredirect/browser_extension/blob/759e403883981a39d14458eab9015fe2cf5a8627/src/pages/options/widgets/general.js#L152

The popup is non-functional. Options and extension seem to work otherwise.

**Comment by ManeraKai** [comment]
I'll hot release. Don't close this issue as I didn't solve the printed error yet (it's not affecting anything rn).
