### ISSUE TITLE
Unable to fetch public instances on Brave v.2.8.3

### ISSUE THREAD

**Issue by Luiz-C-Lima** [libredirect/browser_extension#906]
I upgraded Libredirect from 2.8.1 to 2.8.3, but after the update Libredirect lost all my settings and was unable to fetch public instances, I tried to fetch them with both GitHub and Codeberg. A way that I found to fix it was to remove 2.8.3, install 2.8.2 fetch the instances and then upgrade back to 2.8.3. 

To test I installed Ungoogled Chromium and added Libredirect 2.8.3, on Ungoogled Chromium the extension could fetch the public instances without a problem, the problem appears to be happening only on Brave.

![20240317_21h27m20s_grim](https://github.com/libredirect/browser_extension/assets/54924297/9a56d2d6-cb85-4bbc-bccd-c4787977065e)

Brave displays the following errors on Libredirect

![20240317_21h36m22s_grim](https://github.com/libredirect/browser_extension/assets/54924297/7d2b8e71-8bc7-4d38-99b3-e81a6b21a154)
![20240317_21h36m15s_grim](https://github.com/libredirect/browser_extension/assets/54924297/ea070aa0-1a60-40f7-ba0a-c01f53cac1a9)
![20240317_21h36m06s_grim](https://github.com/libredirect/browser_extension/assets/54924297/35c68ef6-1fc8-4516-b683-becf2721cf9c)
![20240317_21h36m04s_grim](https://github.com/libredirect/browser_extension/assets/54924297/222d1bd3-5f5b-4229-93b3-a9fa5f723a50)
![20240317_21h36m50s_grim](https://github.com/libredirect/browser_extension/assets/54924297/07fd12f5-bc48-4952-8d0f-4cd00dbf8fbb)
![20240317_21h36m43s_grim](https://github.com/libredirect/browser_extension/assets/54924297/d8e0ba27-d273-4d33-ab9a-aaae1d81b5e0)

**Comment by albert-softie** [comment]
having the same problem on vivaldi v6.6.3271.55, it might be impacting other chromium forks too

**Comment by ManeraKai** [comment]
The way of upgrading directly from 2.8.1 => 2.8.3 is making the problem.

**Comment by ManeraKai** [comment]
It's a matter of data not being correctly converted. I'll try to prevent that in future versions.
