### ISSUE TITLE
Unrecognized manifest key 'browser_specific_settings'.

### ISSUE THREAD

**Issue by WoefulWrecker** [libredirect/browser_extension#911]
Brave is up-to-date
[Version 1.64.109 Chromium: 123.0.6312.58 (Official Build) (x86_64)](https://brave.com/latest/)

LibRedirect : 2.8.1

![libredirect](https://github.com/libredirect/browser_extension/assets/54433630/eb4b78a9-e6a0-45f3-ace8-fd6b8830213a)

**Comment by WoefulWrecker** [comment]
Upgrade to a newer version

**Comment by ManeraKai** [comment]
It's something [specific to Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings). You can safely ignore this warning
