### ISSUE TITLE
Instagram redirect giving error

### ISSUE THREAD

**Issue by Heus-Sueh** [libredirect/browser_extension#916]
when enabling the instagram option this is what happens when it tries to redirect to an open source frontend:

[Kooha-2024-04-17-16-22-21.webm](https://github.com/libredirect/browser_extension/assets/98482469/70e4d8a2-738b-432a-aa92-f132c0ee0c5c)

**Comment by ManeraKai** [comment]
When you are in Instagram, you don't press "Switch Instance", you press "Redirect" at the top. When you are in an instance link, you can press "Switch Instance".

**Comment by Heus-Sueh** [comment]
> When you are in Instagram, you don't press "Switch Instance", you press "Redirect" at the top. When you are in an instance link, you can press "Switch Instance".

clicking on the redirect button causes the same problem unfortunately

**Comment by Heus-Sueh** [comment]
I managed to solve it by removing and adding the instance again, but it's still a very strange bug
