### ISSUE TITLE
Quick instance switching.

### ISSUE THREAD

**Issue by OrginalS** [libredirect/browser_extension#919]
Add an option to quickly switch instances by left clicking on extension icon and only showing more options with a right click or automatically switching instances on page refresh or with a hotkey. When having multiple favorite instances added, sometimes some of them temporarily don't work and instances have to be switched multiple times until a working one is found.

**Comment by OrginalS** [comment]
Yeah, I know about that option. I meant switching instances instantly on left click without showing this menu.
![Screenshot from 2024-05-20 21-04-41](https://github.com/libredirect/browser_extension/assets/36825453/2fc908fc-4b0b-4b8b-a9b6-004eb5622e57)
Thank you for leting me know about the keyboard shortcuts.

**Comment by ManeraKai** [comment]
> Yeah, I know about that option. I meant switching instances instantly on left click without showing this menu.

No not to this extent, but then keyboard shortcuts are for this reason.
