### ISSUE TITLE
Add Streamlink Twitch GUI as Twitch frontend

### ISSUE THREAD

**Issue by Victor239** [libredirect/browser_extension#924]
[Streamlink Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui) is an open-source desktop app built on the open-source [Streamlink CLI](https://streamlink.github.io/). It would be great to be able to launch this from Twitch web links.

**Comment by NoPlagiarism** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/613

Does not have custom protocol

**Comment by ManeraKai** [comment]
Tell me to re-open the issue if it gets a custom protocol.
