### ISSUE TITLE
[Firefox] Instances are not loading.

### ISSUE THREAD

**Issue by HDark15** [libredirect/browser_extension#926]
I just noticed this recently because I have everything set up already, so I don't open the settings on the new update.

Fresh install or reset will show no error. Export and import the settings will show error.

On console
```
Uncaught (in promise) TypeError: options[service] is undefined
    loadPage moz-extension://ba24e14d-ff6b-4b78-a447-ed617ba991dd/pages/options/index.js:119
    async* moz-extension://ba24e14d-ff6b-4b78-a447-ed617ba991dd/pages/options/index.js:345
index.js:119:7
```

**Comment by ManeraKai** [comment]
Are you importing settings data from previous version?

**Comment by ManeraKai** [comment]
So, on a fresh install, you're importing settings. When importing settings, redirections stop working. Right?

**Comment by ManeraKai** [comment]
I see. Can you show me your exported settings file?

**Comment by IkelAtomig** [comment]
Weird, It ain't happening on my VM's
