### ISSUE TITLE
[Feature Request] Allow search redirects from google to other search engines

### ISSUE THREAD

**Issue by TheInfamousAlk** [libredirect/browser_extension#928]
So some applications (like discord) have a feature that lets you highlight text and right click to "Search with Google". It opens up a new tab with a google search. There's no way in discord or other apps that do this to change the search provider. They just open a custom URL. I use Kagi. It would be nice if libredirect could parse the search phrase from one engine and redirect to another engine to fix this. There are a few options for "Search" in libredirect now, but it doesn't redirect in the way or to the places I would like, with configurable search engines.

**Comment by IkelAtomig** [comment]
@ManeraKai - Didn't we have Whoogle and Startpage and removed it. Do you remember the reason.

Not to stall this request, just collecting old insights and see if it's applicable or not.

**Comment by ManeraKai** [comment]
For startpage: https://libredirect.github.io/faq.html#suggest_frontend

**Comment by IkelAtomig** [comment]
But Startpage extension, doesn't redirect. Wasn't it the point of the extension ?

**Comment by ManeraKai** [comment]
For search engines, you don't need redirection. You can just have it as the default search engine in your settings. That's what the Startpage extension does I think. The time where you need proper redirection is when you have to redirect to a random instance (SearXNG, etc...). Even if you want to use a single SearXNG instance, you can just right click the address bar and click "Add to search engine" or something, without needing to rely on LibRedirect.

**Comment by IkelAtomig** [comment]
If so, it wouldn't apply here because Kagi can be add from Search Bar.

**Comment by TheInfamousAlk** [comment]
> For search engines, you don't need redirection. You can just have it as the default search engine in your settings. That's what the Startpage extension does I think. The time where you need proper redirection is when you have to redirect to a random instance (SearXNG, etc...). Even if you want to use a single SearXNG instance, you can just right click the address bar and click "Add to search engine" or something, without needing to rely on LibRedirect.

Normally you'd just search in the search bar, no redirection needed. This use-case is for applications that literally paste in a URL for a different search engine. Like my example above, Discord has a right click menu item when highlighting text "Search with Google". That opens google and searches for the highlighted text. What I'm asking for here is to detect when google (or another search engine) is being used, and take the search terms and put them in my search engine of choice using URL parsing.

**Comment by IkelAtomig** [comment]
I see, you mean to redirect from the apps force them into Google and such.

**Comment by TheInfamousAlk** [comment]
Yes. Or any situation in which you'd end up with a google search, such as clicking directly on a link that *is* a google search, and translating it to a search in another engine.

**Comment by IkelAtomig** [comment]
So, We have focus only on Google in that case.

**Comment by IkelAtomig** [comment]
Yeah, It would be tricky to find out which one is from Start Menu and from the app. Because Start Menu searches are URL which could also be treated as those opened from Browser history too.

**Comment by ManeraKai** [comment]
Should we setup a whole different service called `Google`? So anyone who enables normal `Search` service won't get affected?

**Comment by IkelAtomig** [comment]
If my memory is right, the author referring g to redirects in apps not the actual search.

And yes, we need this separately.
17 Aug 2024,  by ***@***.***:

**Comment by TheInfamousAlk** [comment]
Yeah actual apps will create and open a custom google search link (or bing, if windows does it) and open that link in your default browser. The redirect would have to happen in the browser since we can't get these apps to use a different search engine.

**Comment by ManeraKai** [comment]
Now you can redirect both Google and Bing.
