### ISSUE TITLE
UI unusable (v2.8.4)

### ISSUE THREAD

**Issue by atomGit** [libredirect/browser_extension#929]
a UI change between 2.8.2 and 2.8.4 has made the toolbar pop-up unusable

when clicking the toolbar icon > settings > youtube (for ex., but it doesn't matter), the UI becomes very narrow (about 3/4" wide) and all of the content is squashed into this very long, narrow container which is unusable (i couldn't get a screen cap because the pop-up disappears)

it seems like there may be a conflict with some other CSS

accessing the settings from about:addons > preferences works fine

**Comment by ManeraKai** [comment]
Can you take a screenshot?

**Comment by atomGit** [comment]
when i try to screen-cap, the pop-up UI disappears before the capture is made

**Comment by ManeraKai** [comment]
How about recording a video?

**Comment by atomGit** [comment]
taking a screen cap using a delay worked

![1](https://github.com/libredirect/browser_extension/assets/1817307/f70aa165-16c9-4545-a3a2-ff992bc20cf4)
![2](https://github.com/libredirect/browser_extension/assets/1817307/5a0667a9-de1d-49e6-bddb-daed329d2170)
![3](https://github.com/libredirect/browser_extension/assets/1817307/516cd5d9-9ad2-4b87-80f5-16e9d7637b1e)

**Comment by ManeraKai** [comment]
You were doing it like this right?

https://github.com/libredirect/browser_extension/assets/40805353/c9def7ec-5212-4ffa-abfe-b3103dedb2c2

**Comment by atomGit** [comment]
ok, i see what's happening - ignore my 3rd screen cap (i deleted it) - in your video, you click 'settings' and the large UI opens - in my case i'm seeing what's in my 2nd screen cap instead of the whole UI

**Comment by ManeraKai** [comment]
Your problem is because of this commit which was made for mobile devices: https://github.com/libredirect/browser_extension/commit/8d944834fafe683d2d266252747d42a6317f5acf

What happens when you press YouTube in the popup?
What browser are you using?

**Comment by atomGit** [comment]
FF v125

if i click youtube right after opening the pop-up, something like an iframe is displayed which loads youtube.com

**Comment by ManeraKai** [comment]
I rewrote the UI in Svelte. Do you still have the same issue?

**Comment by atomGit** [comment]
no - the settings link in the pop-up loads the new settings page
