### ISSUE TITLE
Automatic management of enabled instances

### ISSUE THREAD

**Issue by mooreye** [libredirect/browser_extension#933]
1. If an enabled instance is no longer on the selectable list, remove it.
2. If a new selectable instance is added, enable it.
3. Maybe also ping them beforehand and if unreachable, don't enable.

This could either happen automatically, for example once a week, or on a click of a button. Managing and checking enabled Searx instances by hand is very tedious.

**Comment by IkelAtomig** [comment]
1. we have an issue there, what if it's a custom instance that's not on the list, maybe say we solve it by marking so when a user adds,But on the other hand we would be storing older instance list so as to remove them which would fill up disk space on the user's side.
2. Feels like you want to enable everything that is just new.
3. We can ping them, but it's up to the user to enable them or not. We don't decided for them, it is their decision.

I could see that, you want a list that is to be enabled which has the best instances like AI. No offense, just my foresight.

**Comment by DDzwiedziu** [comment]
Ad 2, then how a user is supposed to select instances? A new user is presented with a list of instances probably not knowing any of them.
Ad 3, enable instances that are responding and have ping below 100/250/500/1000ms. If resources permit one could implement randomization based on negative weighting (the bigger the ping the lower the chances). No need for such a resource hog as AI to do this.

I'd also argue that switching between different frontends, if available, could be a possibility to get people acquainted with more of them.

**Comment by IkelAtomig** [comment]
2. We do have default instance for every frontend to get started as of now.
3. @ManeraKai Did we have this Ping and enable before. I remember that we did and removed being so buggy.

**Comment by DDzwiedziu** [comment]
Ad 2: I found some of the defaults not working. Just now, to ensure it's a problem, the default Binternet instance for Pinterest gives HTTP502 and Wikiless.org TLS cert is overdue and libredirect shows this as „Server not found”.

**Comment by IkelAtomig** [comment]
Would you mind sharing those defaults, we will shift them to those that have been in the long run for a while.

For binternet, We just added it but not fully supported. Maybe we need to tag it as such. Binternet develoeper doesn't follow the URL scheme of Pinterest, such that, we could replace the domain alone. 

The URL schema is totally different and is linked to the source file of the pinterest. You could check issues both here and on the Binternet repo.

For Wikiless, it was scraped from a Internet archive page. We will change it too in next update.

**Comment by DDzwiedziu** [comment]
Quickly checking:

- https://binternet.ahwx.org/
- https://proxigram.privacyfrontends.repl.co/
- https://pb.bloat.cat/ (Priviblur, 5000ms+)
- https://mikuinv.resrv.org/ (Bilibili, 5000ms+)

**Comment by IkelAtomig** [comment]
@DDzwiedziu - Thanks for the info, it has went off-topic, would you please open it as a separate issue as "Change of inactive default instances to reliable once" and file it.

**Comment by ManeraKai** [comment]
This will not be automatic per say, but interactive: https://github.com/libredirect/browser_extension/commit/1492345b0d2f0f4d6d4a7a6f8814596785a472b0
