### ISSUE TITLE
Reinstating Nitter

### ISSUE THREAD

**Issue by aritus007** [libredirect/browser_extension#934]
There is no "Twitter" option within the Add-on's Preferences Page. 

Is redirecting Twitter an option, or is taken out? 

Thanx

**Comment by IkelAtomig** [comment]
It is taken out. The original project that is used to redirect Twitter, Nitter is dead.

**Comment by pm4rcin** [comment]
@IkelAtomig since nitter is working again maybe it's time to revisit? Not sure if we should ask some instance maintainers first because it could spawn a lot of traffic (maybe, maybe not)? https://status.d420.de/

**Comment by IkelAtomig** [comment]
In my Opinion, Why not ?

But I would like to hear the community input and also from fellow team member hear. We need to more decisive about this. Let's see about this shortly.

**Comment by ManeraKai** [comment]
It's not working again or something. The website explained it well: https://status.d420.de/rip

**Comment by pm4rcin** [comment]
I have used nitter.poast.org for a long time. Recently xcancel.com is my go to as the RSS works there. Yesterday those red instances were all green so either something's changed or they don't have enough real accounts.

**Comment by IkelAtomig** [comment]
Now, Most of the instances that seemed working seems to be down with only top 3 left out.

**Comment by ivan-gj** [comment]
Hello! 
There is (I believe) no reason to delete these settings from the extension, as the user can do it themselves if the project is not working anymore... and, as we've seen many times, these things come back eventually, always. Specially for such big websites. 

So, yes, please, bring back Twitter redirections!

**Comment by ManeraKai** [comment]
Alright
