### ISSUE TITLE
Using favorites as Backup for broken ones

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/browser_extension#936]
Currently when we have more than one instance loaded in favorite list. It always goes to the instances randomly instead of a fixed one.

What do I prefer here is - We pin a instance as default in favorite instances and other instances are also there.

When a redirect is made, it always goes to the default instance. And the remaining is used as Backup for switch Instance in case the default is broken or blocked by 429, too many requests..

**Comment by ManeraKai** [comment]
offline, 429, 403: make a popup to ask the user if he wants to switch, remove, or auto pick a new instance.

**Comment by ManeraKai** [comment]
For now, I won't add the offline error.
