### ISSUE TITLE
Add RAT (Rat Aint Tieba)

### ISSUE THREAD

**Issue by gigirassy** [libredirect/browser_extension#937]
RAT is a pretty new frontend for the Chinese discussion board site Baidu Tieba. It has Chinese language UI exclusively.

Code: https://0xacab.org/johnxina/rat
Instance: https://rat.fis.land/ , https://ti.opnxng.com/ . These are the two I know of.
Instance List: Can't find any instance list on the Git page; but I might be looking wrong because I do not speak/read Chinese. If someone knows of an instance list, feel free to post it here.
For: https://tieba.baidu.com

Thought it'd be nice to add.

**Comment by ManeraKai** [comment]
How to redirect from tieba.baidu.com to it?

**Comment by gigirassy** [comment]
Replace tieba.baidu.com in the URL with the frontend link, and remove &ie=utf-8 from it if it's in the link. Chinese character support is essential, as Baidu Tieba is Chinese-language.
