### ISSUE TITLE
Some default instances are not working

### ISSUE THREAD

**Issue by DDzwiedziu** [libredirect/browser_extension#939]
“Forked” from #933, where an automated fix could prevent this issue.

The default Binternet instance for Pinterest gives HTTP502 and Wikiless.org TLS cert is overdue and libredirect shows this as „Server not found”.

Quickly checking:

    https://binternet.ahwx.org/
    https://proxigram.privacyfrontends.repl.co/
    https://pb.bloat.cat/ (Priviblur, 5000ms+)
    https://mikuinv.resrv.org/ (Bilibili, 5000ms+)

**Comment by ManeraKai** [comment]
> “Forked” from https://github.com/libredirect/browser_extension/issues/933, where an automated fix could prevent this issue.

Default instances are chosen by us, not automation.
