### ISSUE TITLE
Add Materialious https://github.com/Materialious/Materialious

### ISSUE THREAD

**Issue by toyboatcash** [libredirect/browser_extension#944]
[Materialious](https://github.com/Materialious/Materialious)
Instances:Public instances

    Location: New Zealand
    Threads: 6
    IPV6 rotation: Yes
    Man in the Middle: No
    Accounts: Yes
    RYD-Proxy: Yes
    Syncious integration: Yes
    Self-hosted PeerJS: No 

    Location: Ukraine
    Threads: 6
    IPV6 rotation: Yes
    Man in the Middle: No
    Accounts: Yes
    RYD-Proxy: Yes
    Syncious integration: Yes
    Self-hosted PeerJS: Yes 

    Location: Germany
    Threads: 6
    IPV6 rotation: Yes
    Man in the Middle: No
    Accounts: Yes
    RYD-Proxy: No
    Syncious integration: No
    Self-hosted PeerJS: No

**Comment by NoPlagiarism** [comment]
Public Instances are here: https://github.com/Materialious/Materialious/blob/main/docs/INSTANCES.md
Raw: `https://raw.githubusercontent.com/Materialious/Materialious/main/docs/INSTANCES.md`
