### ISSUE TITLE
Add SkunkyArt (DeviantArt Frontend)

### ISSUE THREAD

**Issue by DrWhoFan13** [libredirect/browser_extension#948]
Source Code: [https://git.macaw.me/skunky/SkunkyArt](https://git.macaw.me/skunky/SkunkyArt)

Known instances: [https://skunky.bloat.cat/](https://skunky.bloat.cat/)

For: DeviantArt.com

**Comment by ManeraKai** [comment]
How to redirect it's links?

**Comment by user451421541757324** [comment]
> How to redirect it's links?

- Search: https://www.deviantart.com/search?q=the+hobbit -> https://skunkyart.frontendfriendly.xyz/search?q=the+hobbit&scope=all
- Art: https://www.deviantart.com/chaoyuanxu/art/The-Hobbit-356347115 -> https://skunkyart.frontendfriendly.xyz/post/art/The-Hobbit-356347115
- Profile: https://www.deviantart.com/chaoyuanxu -> https://skunkyart.frontendfriendly.xyz/user/ChaoyuanXu
- Gallery: https://www.deviantart.com/chaoyuanxu/gallery -> https://skunkyart.frontendfriendly.xyz/user/ChaoyuanXu?a=gallery
