### ISSUE TITLE
Bring Back Twitter Redirect

### ISSUE THREAD

**Issue by Alex9001** [libredirect/browser_extension#952]
https://nitter.poast.org is a working nitter redirect

please add nitter back to libredirect and use that as a redirect source

**Comment by ManeraKai** [comment]
https://github.com/libredirect/browser_extension/commit/ffcb0a887376aa6ecbefd69bbb2d074a46555efa

**Comment by cameronj86** [comment]
Late to the party but glad to see it was reinstated. It makes sense to sunset services that have been archived to avoid confusion, but I'm glad that I can still use libredirect when self-hosting said sunset projects
