### ISSUE TITLE
No longer works after I upgraded to Freetube 0.21

### ISSUE THREAD

**Issue by roldengarm** [libredirect/browser_extension#953]
This week I upgraded to Freetube 0.21.0 and then 0.21.1, but Libredirect has stopped working on youtube.com
Page stays white (as before), but doesn't open Freetube.

Have rebooted PC, no difference. No errors either.

**Comment by IkelAtomig** [comment]
We need details such as Browser and OS. That would help it. Worked for me just fine when clicking a youtube link from search results.

**Comment by IkelAtomig** [comment]
Alright, We devs are Linux users, will check it in our VM and look on it. P.S. It's Windows 10 not 11.

**Comment by berenddeschouwer** [comment]
I've got a similar problem on:
- Firefox 128
- Freetube 0.21beta
- Linux (debian testing)

It started very recently, but I don't know if that's because of Firefox 127 -> 128, or a new Freetube.

**Comment by rustyechelle** [comment]
same here, happens just today

i upgraded to firefox 128 yesterday and it was still working, maybe a minor firefox update or just the firefox reboot ?
i upgraded to freetube v0.21.1 the day before that

**Comment by IkelAtomig** [comment]
To be honest this is absurd. I think we need to spin a lot of VMs to check this through. Cuz in our original machines they work great.

**Comment by berenddeschouwer** [comment]
It seems to depend on how youtube is started.

I'll try and narrow down test cases.  If I manage to write a minimal .html page that triggers it, I'll post it.

For now, the following describes the behaviour I find.

Fail:
- start firefox
- click on a youtube link, in a page that's setup to open in a new tab
- new tab opens, url is youtube
- freetube does not open
- refresh works

Success:
- start firefox
- middle click on a youtube link "open in new tab"
- new tab opens, url is youtube
- freetube opens

Success:
- start firefox
- youtube embedded page
- play
- click "open in youtube" in the video
- new tab opens, about:blank
- freetube opens

Speculation:

It depends on target=_blank and rel=noreferrer, or it depends on what Firefox thinks is a deliberate, user-driven (middle click) open-tab action vs. implicit open-tab action.

**Comment by IkelAtomig** [comment]
The first action seems to be after updating to Firefox v128. I was able to redirect to FreeTube in v127 when the issue was filed here.

I searched for a YouTube Video in Startpage which by default opens link in New tab. Yep, you are right. @berenddeschouwer - Thanks for the heads up. It really narrowed it down.

**Comment by ManeraKai** [comment]
Apparently it's security feature, try adding this to an html page:
`<a href="freetube://https://youtube.com/" target="_blank" rel="noopener nofollow noreferrer">Click me!</a>`
[rel=noreferrer](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noreferrer)
