### ISSUE TITLE
Unable to fetch public instances on Brave v.2.8.5

### ISSUE THREAD

**Issue by Luiz-C-Lima** [libredirect/browser_extension#955]
I upgraded Libredirect from 2.8.4 to 2.8.5, but after the update Libredirect lost all my settings and was unable to fetch public instances, I tried to fetch them with both GitHub and Codeberg.

To test I installed Ungoogled Chromium and added Libredirect 2.8.5, on Ungoogled Chromium the extension could fetch the public instances without a problem, the problem appears to be happening only on Brave.

This appears to be the exact same issue as a few months back in #906, but now I don't have a version to downgrade and grab the public instances.

Brave displays the following errors on Libredirect

![1](https://github.com/user-attachments/assets/d570ead6-62c2-4ec8-925b-ac8797102ce8)
![2](https://github.com/user-attachments/assets/f346a27a-3c09-4a66-861c-c31ae8f48cd3)
![3](https://github.com/user-attachments/assets/e4d3590d-7935-41ee-925b-ed759b841f3a)
![4](https://github.com/user-attachments/assets/fb947668-83a7-4988-8011-5ae743b1f7a2)
![5](https://github.com/user-attachments/assets/3eb9ff08-e8dd-464b-9a01-50ebfbc7c953)
![6](https://github.com/user-attachments/assets/941aae89-4bb8-4d5e-94a1-a5b7fa7c8588)

**Comment by ManeraKai** [comment]
Is the problem still happening?

**Comment by Luiz-C-Lima** [comment]
> Is the problem still happening? I checked Brave Version 1.68.141 Chromium: 127.0.6533.120 and it's working correctly.

No, it has been fixed with 2.9.0, thanks, I just forgot to close the issue.
