### ISSUE TITLE
Export Settings only works in a separate moz-extension:// tab (Firefox, Android)

### ISSUE THREAD

**Issue by v1s7** [libredirect/browser_extension#956]
https://github.com/user-attachments/assets/5339b8b5-47e8-4f81-8fc0-148433178080

Versions:
Firefox (Mull): 127.0.2
Android: 13
LibRedirect: 2.8.5

**Comment by mkalinski** [comment]
I can add that Import Settings also fails silently in the settings tab opened from menu, and only works in the separate tab.

Thanks for the workaround, saved me a lot of headache.
