### ISSUE TITLE
Libredirect Having Trouble Loading Instances On I2P

### ISSUE THREAD

**Issue by ghost** [libredirect/browser_extension#959]
Libredirect can't seem to load any previously added instances & won't let me add new ones while I'm using I2P. It's stuck forever loading. When I'm on the clearnet, it works just fine. But for some reason, it stopped working on I2P.
Edit: On the clearnet, it will let me manually add some instances, but not others, especially if they're not on the official lists.
![image](https://github.com/user-attachments/assets/dbe67135-f273-4dbd-8bcb-3d143a846bfb)

**Comment by ManeraKai** [comment]
> Libredirect can't seem to load any previously added instances & won't let me add new ones while I'm using I2P. It's stuck forever loading. When I'm on the clearnet, it works just fine. But for some reason, it stopped working on I2P.

Well, it is trying to connect to https://raw.githubusercontent.com/libredirect/instances/main/data.json which you can't do without an exit node.

**Comment by ManeraKai** [comment]
>  Edit: On the clearnet, it will let me manually add some instances, but not others, especially if they're not on the official lists.

This is weird, give me an example.
