### ISSUE TITLE
Pair of annoyances with Rimgo

### ISSUE THREAD

**Issue by AresUII** [libredirect/browser_extension#960]
**Procedure A**

1. Click on a link to imgur

Intent & usual result:

Get served the image/album via rimgo

What sometimes happens but shouldn't:

I get served https://sudovanilla.org/blog/introducing-sudovanilla-org with no chance to re-roll for a working instance

**Procedure B**

1. Navigate to Settings -> Imgur
2. Under "Frontend", select rimgo

Intent:

View and edit a _favorites list_, similar to what LibRedirect allows for Invidious [red box and harpoon overlaid for emphasis]:
![image](https://github.com/user-attachments/assets/80abcba5-83b6-40c4-b5a7-9fe183f6b00d)

Instead:

No visible favorites list, no ability to remove or disable bad Rimgo instances

Using FF 115.13.0esr and W10 22H2 [both AMD64].

**Comment by ManeraKai** [comment]
Is this still happening in v2.9.1?

**Comment by AresUII** [comment]
> Is this still happening in v2.9.1?

No
