### ISSUE TITLE
PixivFE public instances

### ISSUE THREAD

**Issue by SinnySupernova** [libredirect/browser_extension#965]
The list of public instances for PixivFE isn't loaded
 
page: https://pixivfe.pages.dev/public-image-proxies/
repo: https://gitlab.com/pixivfe/pixivfe-docs

**Comment by ManeraKai** [comment]
You should open the issue here: https://github.com/libredirect/instances, or a PR is welcome :)

**Comment by ManeraKai** [comment]
Fixed it, no need for a PR :smiling_face_with_tear:
