### ISSUE TITLE
Weblate Stops

### ISSUE THREAD

**Issue by maboroshin** [libredirect/browser_extension#979]
Frequent project stoppages in Weblate translation tool. It has been suspended for 3 months from May 2024. If you have discarded Weblate, please revise the README.

https://hosted.weblate.org/projects/libredirect/extension/#alerts

For this reason, #976 is PL'd directly.

Note: In other words, it seems that the service may be down and unnoticed. I see this frequently on Weblate. I have not seen this on Transifex or Crowdin.

**Comment by ManeraKai** [comment]
Weblate is hard 😫

**Comment by maboroshin** [comment]
I see. There is also a way to stop WEBLATE. Because, Only Weblate is frequently down for service. And, you are having difficulty dealing with this.

You could mention in the README that you reverted to the PL method because Weblate is difficult to use.

**Comment by ManeraKai** [comment]
I just accepted the PR's as a temporarily solution till I fix weblate.
