### ISSUE TITLE
Search opens the homepage

### ISSUE THREAD

**Issue by itscool900** [libredirect/browser_extension#987]
Searching with the LibRedirect search (set to SearXNG) sometimes opens the homepage instead of the query typed in. The only instances I remember that do this is https://search.rowie.at, https://searx.mv-software.de/, and https://search.gcomm.ch.

**Comment by qrhfz** [comment]
the weird thing is that when it happens and i try to repeat it by only activating the instance, it works correctly the second time.

**Comment by ManeraKai** [comment]
I think this is a duplicate of https://github.com/libredirect/browser_extension/issues/880.

**Comment by itscool900** [comment]
Yes, it is. How do I redirect this to that? Should I just close with comment 'duplicate of #880'?

**Comment by ManeraKai** [comment]
> Yes, it is. How do I redirect this to that? Should I just close with comment 'duplicate of https://github.com/libredirect/browser_extension/issues/880'?

Yes, close this as a duplicate.

> Also, is there a way to re open the issue?

Not in GitHub. You can in Codeberg though.
