### ISSUE TITLE
Allow users to manually define a redirect rule

### ISSUE THREAD

**Issue by nileshtrivedi** [libredirect/browser_extension#989]
I wanted to redirect links for arxiv.org to alphaxiv.org. This is not for better privacy, but for personal preference and convenience.
I could not figure out how to achieve this with libredirect. This would make a good feature.

**Comment by ManeraKai** [comment]
For any custom redirects, I recommend you use [Redirector](https://einaregilsson.com/redirector/).

**Comment by nileshtrivedi** [comment]
Thanks @ManeraKai . That works. Closing this issue.
