### ISSUE TITLE
ability to disable the Error message window through a toggle ? 

### ISSUE THREAD

**Issue by YAKSL** [libredirect/browser_extension#992]
the current behavior of the error window is it's opening in the current tab even when i'm on a website that's not related to any redirect rule, also when the redirect website functions correctly but the fact that libredirect detects that it gave some error the error window still opens which is kinda annoying. the error message should at least open in a new window not redirect to it to begin with

![Snapshot](https://github.com/user-attachments/assets/f7680d44-1a86-475c-8e8d-74eb81fb2b8f)

**Comment by YAKSL** [comment]
the only fix for this is to use the previous version (2.9.1) for now

**Comment by ManeraKai** [comment]
What happens when you press Switch Instance?

**Comment by nc7s** [comment]
Happens here too. It goes into this screen for **any** failed request, which in my case includes `mqdefault.jpg` and `favicon.ico`. I think this is a nice feature, but it's bizarre to see the switch went to some placeholder image.

**Comment by nc7s** [comment]
And it even goes to this error page even if I disabled the redirect (in this case Youtube for an Invidious instance).

**Comment by smaragdus** [comment]
Version [3.0.0](https://github.com/libredirect/browser_extension/releases/tag/v3.0.0) makes [LibRedirect](https://libredirect.github.io/) totally unusable on Firefox mobile as one cannot downgrade to the last good version ([2.9.1](https://github.com/libredirect/browser_extension/releases/tag/v2.9.1)) and one cannot prevent the extension to update to the latest faulty version ([3.0.0](https://github.com/libredirect/browser_extension/releases/tag/v3.0.0)) either. One must be really quick to copy the redirect link before the error message appears and paste it into another browser. This happens with [one Nitter instance](https://nitter.poast.org/) which appears to be performing some stupid browser check. So currently I am forced to go to my old practice of copying original links and manually editing them in a text editor. I think that [LibRedirect](https://libredirect.github.io/) should just redirect links according to user's choices, not spewing some false error messages. The most important principle in software development is "If it works, don't fix it!".

**Comment by YAKSL** [comment]
> What happens when you press Switch Instance?
> 
> And show me a URL and your settings. I'm not able to reproduce it.

it happens with this one https://youtube.com/watch?v=kIVdN9rG748 on https://inv.nadeko.net as the instance (HD720 quality), and on other videos/instances too. i haven't tested it on other frontends before downgrading

**Comment by ManeraKai** [comment]
I think having those buttons in the popup will be better.

**Comment by ManeraKai** [comment]
> Version [3.0.0](https://github.com/libredirect/browser_extension/releases/tag/v3.0.0) makes [LibRedirect](https://libredirect.github.io/) totally unusable on Firefox mobile as one cannot downgrade to the last good version ([2.9.1](https://github.com/libredirect/browser_extension/releases/tag/v2.9.1)) and one cannot prevent the extension to update to the latest faulty version ([3.0.0](https://github.com/libredirect/browser_extension/releases/tag/v3.0.0)) either.

I will remove the listener for the server errors as a hotfix. Later, I will migrate the buttons to the popup.

**Comment by ManeraKai** [comment]
If you have a single instance:
![image](https://github.com/user-attachments/assets/23852a51-98b3-4727-b5f8-31fcb5f64287)
If you have multiple instances:
![image](https://github.com/user-attachments/assets/1a6d5c88-efe5-4727-824d-c74f083a9d05)
