### ISSUE TITLE
extra slash forced on custom instances

### ISSUE THREAD

**Issue by iamwacko** [libredirect/browser_extension#996]
on Firefox, libredirect 3.0.0

I added a custom invidious instance, and was trying to use it, when I noticed that I kept getting redirected to the homepage. I did a little digging with inspect, and it seems that I was getting a 302 because of the double slashes. The non-custom instances don't have that slash. I didn't find anything about similar issues in the issue trackers, and custom instances I added previously didn't have the extra slash.

Reproduction steps:
1. Go to libredirect Youtube settings, copy one of the default instances, paste it into the "custom" box, and hit plus
2. Remove any other favorite, so it has to use the custom instance
3. Go to https://www.youtube.com/youtube, and witness how it won't go to YouTube's channel, but instead the homepage (you can also try with any other channel or video link)

**Comment by cameronj86** [comment]
Samesies.

Ironically I experienced the same thing just now and was about to load a tix. All of my existing custom instances are unaffected but I can't add anything new

**Comment by ManeraKai** [comment]
This link will go to YouTube's channel: https://www.youtube.com/@youtube

**Comment by AresUII** [comment]
Not properly fixed as of 3.0.1. See #999.

**Comment by iamwacko** [comment]
> Not properly fixed as of 3.0.1. See #999.

The fix was committed after 3.0.1 was released, so that's not surprising
